import { DIFFICULTY } from "./difficulty";

export const EXERCISE_LIBRARY = {
  // ==========================
  // UPPER BODY
  // ==========================

  "Push Up": {
    name: "Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    movementPattern: "Horizontal Push",
    analyticsName: "Push Up",
  },

  "Bench Press": {
    name: "Bench Press",
    aliases: ["Flat Bench"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    movementPattern: "Horizontal Push",
    analyticsName: "Bench Press",
  },

  "Incline Bench Press": {
    name: "Incline Bench Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Front Delts", "Triceps"],
    movementPattern: "Incline Push",
    analyticsName: "Incline Bench Press",
  },

  "Chest Fly": {
    name: "Chest Fly",
    aliases: ["Dumbbell Fly"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "Chest Fly",
  },

  "Pull Up": {
    name: "Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Upper Back"],
    movementPattern: "Vertical Pull",
    analyticsName: "Pull Up",
  },

  "Chin Up": {
    name: "Chin Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Lats"],
    movementPattern: "Vertical Pull",
    analyticsName: "Chin Up",
  },

  "Lat Pulldown": {
    name: "Lat Pulldown",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Lat Pulldown",
  },

  "Bent Over Row": {
    name: "Bent Over Row",
    aliases: ["Barbell Row"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Lats", "Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Bent Over Row",
  },

  "Seated Cable Row": {
    name: "Seated Cable Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Lats", "Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Seated Cable Row",
  },

  Dip: {
    name: "Dip",
    aliases: ["Parallel Bar Dip"],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dip Bars",
    primaryMuscles: ["Chest", "Triceps"],
    secondaryMuscles: ["Front Delts"],
    movementPattern: "Vertical Push",
    analyticsName: "Dip",
  },

  "Shoulder Press": {
    name: "Shoulder Press",
    aliases: ["Overhead Press"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Shoulder Press",
  },

  "Lateral Raise": {
    name: "Lateral Raise",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Side Delts"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Lateral Raise",
  },

  "Bicep Curl": {
    name: "Bicep Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Bicep Curl",
  },

  "Tricep Pushdown": {
    name: "Tricep Pushdown",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Tricep Pushdown",
  },

  "Muscle Up": {
    name: "Muscle Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats", "Chest"],
    secondaryMuscles: ["Shoulders", "Biceps", "Triceps"],
    movementPattern: "Explosive Pull",
    analyticsName: "Muscle Up",
  },

  "Arnold Press": {
    name: "Arnold Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dumbbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Arnold Press",
  },

  "Australian Row": {
    name: "Australian Row",
    aliases: ["Bodyweight Row", "Inverted Row"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bar",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Australian Row",
  },

  "Cable Curl": {
    name: "Cable Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Cable Curl",
  },

  "Cable Fly": {
    name: "Cable Fly",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "Cable Fly",
  },

  "Cable Row": {
    name: "Cable Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Cable Row",
  },

  "Chest Dip": {
    name: "Chest Dip",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dip Bars",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Chest Dip",
  },

  "Chest Press Machine": {
    name: "Chest Press Machine",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Chest Press Machine",
  },

  "Chest Supported Row": {
    name: "Chest Supported Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Chest Supported Row",
  },

  "Close Grip Bench Press": {
    name: "Close Grip Bench Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Barbell",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Chest"],
    movementPattern: "Horizontal Push",
    analyticsName: "Close Grip Bench Press",
  },

  "Close Grip Pull Up": {
    name: "Close Grip Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Close Grip Pull Up",
  },

  "Concentration Curl": {
    name: "Concentration Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Concentration Curl",
  },

  "Decline Bench Press": {
    name: "Decline Bench Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Lower Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Decline Bench Press",
  },

  "Decline Push Up": {
    name: "Decline Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Decline Push Up",
  },

  "Diamond Push Up": {
    name: "Diamond Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Chest"],
    movementPattern: "Horizontal Push",
    analyticsName: "Diamond Push Up",
  },

  "Dumbbell Bench Press": {
    name: "Dumbbell Bench Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Dumbbell Bench Press",
  },

  "Dumbbell Curl": {
    name: "Dumbbell Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Dumbbell Curl",
  },

  "Dumbbell Pullover": {
    name: "Dumbbell Pullover",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dumbbell",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Chest"],
    movementPattern: "Pull",
    analyticsName: "Dumbbell Pullover",
  },

  "Dumbbell Row": {
    name: "Dumbbell Row",
    aliases: ["One Arm Row"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Dumbbell Row",
  },

  "Dumbbell Shoulder Press": {
    name: "Dumbbell Shoulder Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Dumbbell Shoulder Press",
  },

  "EZ Bar Curl": {
    name: "EZ Bar Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "EZ Bar",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "EZ Bar Curl",
  },

  "Face Pull": {
    name: "Face Pull",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Upper Back"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Face Pull",
  },

  "Farmer Carry": {
    name: "Farmer Carry",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dumbbell",
    primaryMuscles: ["Forearms"],
    secondaryMuscles: ["Traps", "Core"],
    movementPattern: "Carry",
    analyticsName: "Farmer Carry",
  },

  "Flat Bench Dumbbell Fly": {
    name: "Flat Bench Dumbbell Fly",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "Flat Bench Dumbbell Fly",
  },

  "Front Raise": {
    name: "Front Raise",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Front Delts"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Front Raise",
  },

  "Hammer Curl": {
    name: "Hammer Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    movementPattern: "Isolation",
    analyticsName: "Hammer Curl",
  },

  "Handstand Push Up": {
    name: "Handstand Push Up",
    aliases: ["HSPU"],
    category: "upperBody",
    type: "dynamic",
    tier: 4,
    difficulty: DIFFICULTY.TIER_4,
    equipment: "Bodyweight",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Handstand Push Up",
  },

  "High Cable Fly": {
    name: "High Cable Fly",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "High Cable Fly",
  },

  "Hindu Push Up": {
    name: "Hindu Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Hindu Push Up",
  },

  "Incline Dumbbell Press": {
    name: "Incline Dumbbell Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Front Delts"],
    movementPattern: "Incline Push",
    analyticsName: "Incline Dumbbell Press",
  },

  "Incline Push Up": {
    name: "Incline Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Incline Push Up",
  },

  "Machine Shoulder Press": {
    name: "Machine Shoulder Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Machine Shoulder Press",
  },

  "Neutral Grip Pull Up": {
    name: "Neutral Grip Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Neutral Grip Pull Up",
  },

  "One Arm Pull Up": {
    name: "One Arm Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 4,
    difficulty: DIFFICULTY.TIER_4,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "One Arm Pull Up",
  },

  "One Arm Push Up": {
    name: "One Arm Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 4,
    difficulty: DIFFICULTY.TIER_4,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Core"],
    movementPattern: "Horizontal Push",
    analyticsName: "One Arm Push Up",
  },

  "Overhead Tricep Extension": {
    name: "Overhead Tricep Extension",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Overhead Tricep Extension",
  },

  "Pec Deck": {
    name: "Pec Deck",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "Pec Deck",
  },

  "Pike Push Up": {
    name: "Pike Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Pike Push Up",
  },

  "Preacher Curl": {
    name: "Preacher Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "EZ Bar",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Preacher Curl",
  },

  "Pseudo Planche Push Up": {
    name: "Pseudo Planche Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Core"],
    movementPattern: "Horizontal Push",
    analyticsName: "Pseudo Planche Push Up",
  },

    "Rear Delt Fly": {
    name: "Rear Delt Fly",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Upper Back"],
    movementPattern: "Isolation",
    analyticsName: "Rear Delt Fly",
  },

  "Resistance Band Row": {
    name: "Resistance Band Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Resistance Band",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Resistance Band Row",
  },

  "Ring Dip": {
    name: "Ring Dip",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Gymnastic Rings",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Shoulders"],
    movementPattern: "Vertical Push",
    analyticsName: "Ring Dip",
  },

  "Ring Push Up": {
    name: "Ring Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Gymnastic Rings",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Core"],
    movementPattern: "Horizontal Push",
    analyticsName: "Ring Push Up",
  },

  "Ring Row": {
    name: "Ring Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Gymnastic Rings",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Ring Row",
  },

  "Seated Dumbbell Press": {
    name: "Seated Dumbbell Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Seated Dumbbell Press",
  },

  "Shoulder Press Machine": {
    name: "Shoulder Press Machine",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Shoulder Press Machine",
  },

  "Shrugs": {
    name: "Shrugs",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Traps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Shrugs",
  },

  "Skull Crusher": {
    name: "Skull Crusher",
    aliases: ["Lying Tricep Extension"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "EZ Bar",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Skull Crusher",
  },

  "Straight Arm Pulldown": {
    name: "Straight Arm Pulldown",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Lats"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Straight Arm Pulldown",
  },

  "T-Bar Row": {
    name: "T-Bar Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Barbell",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Lats", "Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "T-Bar Row",
  },

  "Typewriter Pull Up": {
    name: "Typewriter Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 4,
    difficulty: DIFFICULTY.TIER_4,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Core"],
    movementPattern: "Vertical Pull",
    analyticsName: "Typewriter Pull Up",
  },

  "Upright Row": {
    name: "Upright Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Traps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Upright Row",
  },

  "Weighted Dip": {
    name: "Weighted Dip",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Dip Belt",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Weighted Dip",
  },

  "Weighted Pull Up": {
    name: "Weighted Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Dip Belt",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Weighted Pull Up",
  },

  "Wide Grip Pull Up": {
    name: "Wide Grip Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Upper Back"],
    movementPattern: "Vertical Pull",
    analyticsName: "Wide Grip Pull Up",
  },

  "Wide Push Up": {
    name: "Wide Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders"],
    movementPattern: "Horizontal Push",
    analyticsName: "Wide Push Up",
  },

    // ==========================
  // LOWER BODY
  // ==========================

  // ==========================
  // BODYWEIGHT SQUAT VARIATIONS
  // ==========================

  "Bodyweight Squat": {
    name: "Bodyweight Squat",
    aliases: ["Air Squat", "Basic Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Squat",
    analyticsName: "Bodyweight Squat",
  },

  "Narrow Stance Squat": {
    name: "Narrow Stance Squat",
    aliases: ["Close Stance Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Calves"],
    movementPattern: "Squat",
    analyticsName: "Narrow Stance Squat",
  },

  "Wide Stance Squat": {
    name: "Wide Stance Squat",
    aliases: ["Wide Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes", "Quadriceps", "Adductors"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Squat",
    analyticsName: "Wide Stance Squat",
  },

  "Sumo Squat": {
    name: "Sumo Squat",
    aliases: ["Plie Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes", "Adductors", "Quadriceps"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Squat",
    analyticsName: "Sumo Squat",
  },

  "Tempo Squat": {
    name: "Tempo Squat",
    aliases: ["Slow Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Squat",
    analyticsName: "Tempo Squat",
  },

  "Pause Squat": {
    name: "Pause Squat",
    aliases: ["Paused Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Squat",
    analyticsName: "Pause Squat",
  },

  "Sissy Squat": {
    name: "Sissy Squat",
    aliases: ["Bodyweight Sissy Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Hip Flexors", "Core"],
    movementPattern: "Knee Extension",
    analyticsName: "Sissy Squat",
  },

  "Assisted Sissy Squat": {
    name: "Assisted Sissy Squat",
    aliases: ["Supported Sissy Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Support",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Hip Flexors", "Core"],
    movementPattern: "Knee Extension",
    analyticsName: "Assisted Sissy Squat",
  },

  "Hindu Squat": {
    name: "Hindu Squat",
    aliases: ["Bethak"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Squat",
    analyticsName: "Hindu Squat",
  },

  "Cossack Squat": {
    name: "Cossack Squat",
    aliases: ["Side-to-Side Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes", "Adductors"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Lateral Squat",
    analyticsName: "Cossack Squat",
  },

  // ==========================
  // WEIGHTED SQUAT VARIATIONS
  // ==========================

  "Back Squat": {
    name: "Back Squat",
    aliases: ["Barbell Back Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core", "Lower Back"],
    movementPattern: "Squat",
    analyticsName: "Back Squat",
  },

  "High Bar Squat": {
    name: "High Bar Squat",
    aliases: ["High Bar Back Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Squat",
    analyticsName: "High Bar Squat",
  },

  "Low Bar Squat": {
    name: "Low Bar Squat",
    aliases: ["Low Bar Back Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings", "Lower Back", "Core"],
    movementPattern: "Squat",
    analyticsName: "Low Bar Squat",
  },

  "Front Squat": {
    name: "Front Squat",
    aliases: ["Barbell Front Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Barbell",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Core", "Upper Back", "Hamstrings"],
    movementPattern: "Squat",
    analyticsName: "Front Squat",
  },

  "Goblet Squat": {
    name: "Goblet Squat",
    aliases: ["Dumbbell Goblet Squat", "Kettlebell Goblet Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell or Kettlebell",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Upper Back"],
    movementPattern: "Squat",
    analyticsName: "Goblet Squat",
  },

  "Zercher Squat": {
    name: "Zercher Squat",
    aliases: [],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Barbell",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Upper Back", "Biceps"],
    movementPattern: "Squat",
    analyticsName: "Zercher Squat",
  },

  "Overhead Squat": {
    name: "Overhead Squat",
    aliases: ["Barbell Overhead Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Barbell",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: [
      "Hamstrings",
      "Core",
      "Shoulders",
      "Upper Back",
      "Calves",
    ],
    movementPattern: "Squat",
    analyticsName: "Overhead Squat",
  },

  "Box Squat": {
    name: "Box Squat",
    aliases: ["Barbell Box Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell and Box",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings", "Core", "Lower Back"],
    movementPattern: "Squat",
    analyticsName: "Box Squat",
  },

  "Safety Bar Squat": {
    name: "Safety Bar Squat",
    aliases: ["Safety Squat Bar Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Safety Squat Bar",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Upper Back"],
    movementPattern: "Squat",
    analyticsName: "Safety Bar Squat",
  },

  "Smith Machine Squat": {
    name: "Smith Machine Squat",
    aliases: ["Smith Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Smith Machine",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Squat",
    analyticsName: "Smith Machine Squat",
  },

  "Hack Squat": {
    name: "Hack Squat",
    aliases: ["Machine Hack Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Hack Squat Machine",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Squat",
    analyticsName: "Hack Squat",
  },

  "Belt Squat": {
    name: "Belt Squat",
    aliases: ["Hip Belt Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Belt Squat Machine",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Squat",
    analyticsName: "Belt Squat",
  },

  // ==========================
  // LUNGES AND SPLIT SQUATS
  // ==========================

  "Forward Lunge": {
    name: "Forward Lunge",
    aliases: ["Front Lunge"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Lunge",
    analyticsName: "Forward Lunge",
  },

  "Reverse Lunge": {
    name: "Reverse Lunge",
    aliases: ["Backward Lunge"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Lunge",
    analyticsName: "Reverse Lunge",
  },

  "Walking Lunge": {
    name: "Walking Lunge",
    aliases: ["Walking Lunges"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Lunge",
    analyticsName: "Walking Lunge",
  },

  "Lateral Lunge": {
    name: "Lateral Lunge",
    aliases: ["Side Lunge"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes", "Adductors", "Quadriceps"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Lateral Lunge",
    analyticsName: "Lateral Lunge",
  },

  "Curtsy Lunge": {
    name: "Curtsy Lunge",
    aliases: ["Cross-Behind Lunge"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Adductors", "Hamstrings", "Core"],
    movementPattern: "Lunge",
    analyticsName: "Curtsy Lunge",
  },

  "Stationary Split Squat": {
    name: "Stationary Split Squat",
    aliases: ["Split Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Split Squat",
    analyticsName: "Stationary Split Squat",
  },

  "Bulgarian Split Squat": {
    name: "Bulgarian Split Squat",
    aliases: ["Rear Foot Elevated Split Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bench",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Split Squat",
    analyticsName: "Bulgarian Split Squat",
  },

  "Dumbbell Bulgarian Split Squat": {
    name: "Dumbbell Bulgarian Split Squat",
    aliases: ["Weighted Bulgarian Split Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dumbbells and Bench",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core", "Forearms"],
    movementPattern: "Split Squat",
    analyticsName: "Dumbbell Bulgarian Split Squat",
  },

  "Jumping Lunge": {
    name: "Jumping Lunge",
    aliases: ["Split Jump", "Jump Lunge"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Jump",
    analyticsName: "Jumping Lunge",
  },

  // ==========================
  // SINGLE-LEG SQUAT VARIATIONS
  // ==========================

  "Assisted Pistol Squat": {
    name: "Assisted Pistol Squat",
    aliases: ["Supported Pistol Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Support",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Single-Leg Squat",
    analyticsName: "Assisted Pistol Squat",
  },

  "Pistol Squat": {
    name: "Pistol Squat",
    aliases: ["Single-Leg Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core", "Hip Flexors"],
    movementPattern: "Single-Leg Squat",
    analyticsName: "Pistol Squat",
  },

  "Box Pistol Squat": {
    name: "Box Pistol Squat",
    aliases: ["Pistol Squat to Box"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Box or Bench",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Single-Leg Squat",
    analyticsName: "Box Pistol Squat",
  },

  "Shrimp Squat": {
    name: "Shrimp Squat",
    aliases: [],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Single-Leg Squat",
    analyticsName: "Shrimp Squat",
  },

  "Skater Squat": {
    name: "Skater Squat",
    aliases: ["Single-Leg Skater Squat"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Single-Leg Squat",
    analyticsName: "Skater Squat",
  },

  // ==========================
  // STEP EXERCISES
  // ==========================

  "Step Up": {
    name: "Step Up",
    aliases: ["Box Step Up"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Box or Bench",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Step",
    analyticsName: "Step Up",
  },

  "Dumbbell Step Up": {
    name: "Dumbbell Step Up",
    aliases: ["Weighted Step Up"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbells and Box",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core", "Forearms"],
    movementPattern: "Step",
    analyticsName: "Dumbbell Step Up",
  },

  "Lateral Step Up": {
    name: "Lateral Step Up",
    aliases: ["Side Step Up"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Box or Bench",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Adductors", "Hamstrings", "Calves"],
    movementPattern: "Lateral Step",
    analyticsName: "Lateral Step Up",
  },

  "Step Down": {
    name: "Step Down",
    aliases: ["Controlled Step Down"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Box or Step",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Calves"],
    movementPattern: "Step",
    analyticsName: "Step Down",
  },

  // ==========================
  // DEADLIFT AND HIP-HINGE VARIATIONS
  // ==========================

  "Conventional Deadlift": {
    name: "Conventional Deadlift",
    aliases: ["Barbell Deadlift", "Deadlift"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Glutes", "Hamstrings", "Lower Back"],
    secondaryMuscles: [
      "Quadriceps",
      "Upper Back",
      "Core",
      "Forearms",
      "Traps",
    ],
    movementPattern: "Hip Hinge",
    analyticsName: "Conventional Deadlift",
  },

  "Sumo Deadlift": {
    name: "Sumo Deadlift",
    aliases: ["Wide Stance Deadlift"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Glutes", "Quadriceps", "Adductors"],
    secondaryMuscles: ["Hamstrings", "Lower Back", "Core", "Forearms"],
    movementPattern: "Hip Hinge",
    analyticsName: "Sumo Deadlift",
  },

  "Romanian Deadlift": {
    name: "Romanian Deadlift",
    aliases: ["RDL"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Lower Back", "Core", "Forearms"],
    movementPattern: "Hip Hinge",
    analyticsName: "Romanian Deadlift",
  },

  "Dumbbell Romanian Deadlift": {
    name: "Dumbbell Romanian Deadlift",
    aliases: ["Dumbbell RDL"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbells",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Lower Back", "Core", "Forearms"],
    movementPattern: "Hip Hinge",
    analyticsName: "Dumbbell Romanian Deadlift",
  },

  "Single-Leg Romanian Deadlift": {
    name: "Single-Leg Romanian Deadlift",
    aliases: ["Single-Leg RDL"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight or Dumbbell",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Calves", "Core", "Lower Back"],
    movementPattern: "Single-Leg Hip Hinge",
    analyticsName: "Single-Leg Romanian Deadlift",
  },

  "Stiff-Leg Deadlift": {
    name: "Stiff-Leg Deadlift",
    aliases: ["Stiff-Legged Deadlift"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Glutes", "Lower Back", "Core"],
    movementPattern: "Hip Hinge",
    analyticsName: "Stiff-Leg Deadlift",
  },

  "Trap Bar Deadlift": {
    name: "Trap Bar Deadlift",
    aliases: ["Hex Bar Deadlift"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Trap Bar",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: [
      "Hamstrings",
      "Lower Back",
      "Core",
      "Forearms",
      "Traps",
    ],
    movementPattern: "Hip Hinge",
    analyticsName: "Trap Bar Deadlift",
  },

  "Good Morning": {
    name: "Good Morning",
    aliases: ["Barbell Good Morning"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Lower Back", "Core"],
    movementPattern: "Hip Hinge",
    analyticsName: "Good Morning",
  },

  "Cable Pull Through": {
    name: "Cable Pull Through",
    aliases: ["Rope Pull Through"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Glutes", "Hamstrings"],
    secondaryMuscles: ["Lower Back", "Core"],
    movementPattern: "Hip Hinge",
    analyticsName: "Cable Pull Through",
  },

  // ==========================
  // GLUTE EXERCISES
  // ==========================

  "Glute Bridge": {
    name: "Glute Bridge",
    aliases: ["Floor Glute Bridge"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Hip Extension",
    analyticsName: "Glute Bridge",
  },

  "Single-Leg Glute Bridge": {
    name: "Single-Leg Glute Bridge",
    aliases: ["One-Leg Glute Bridge"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Single-Leg Hip Extension",
    analyticsName: "Single-Leg Glute Bridge",
  },

  "Hip Thrust": {
    name: "Hip Thrust",
    aliases: ["Bodyweight Hip Thrust"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bench",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Quadriceps", "Core"],
    movementPattern: "Hip Extension",
    analyticsName: "Hip Thrust",
  },

  "Barbell Hip Thrust": {
    name: "Barbell Hip Thrust",
    aliases: ["Weighted Hip Thrust"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell and Bench",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Quadriceps", "Core"],
    movementPattern: "Hip Extension",
    analyticsName: "Barbell Hip Thrust",
  },

  "Frog Pump": {
    name: "Frog Pump",
    aliases: ["Frog Glute Bridge"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings"],
    movementPattern: "Hip Extension",
    analyticsName: "Frog Pump",
  },

  "Donkey Kick": {
    name: "Donkey Kick",
    aliases: ["Quadruped Hip Extension"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Hip Extension",
    analyticsName: "Donkey Kick",
  },

  "Fire Hydrant": {
    name: "Fire Hydrant",
    aliases: ["Quadruped Hip Abduction"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glute Medius"],
    secondaryMuscles: ["Glutes", "Core"],
    movementPattern: "Hip Abduction",
    analyticsName: "Fire Hydrant",
  },

  "Cable Glute Kickback": {
    name: "Cable Glute Kickback",
    aliases: ["Cable Kickback"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Hip Extension",
    analyticsName: "Cable Glute Kickback",
  },

  // ==========================
  // HAMSTRING EXERCISES
  // ==========================

  "Nordic Hamstring Curl": {
    name: "Nordic Hamstring Curl",
    aliases: ["Nordic Curl", "Natural Glute Ham Raise"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight and Anchor",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Glutes", "Calves", "Core"],
    movementPattern: "Knee Flexion",
    analyticsName: "Nordic Hamstring Curl",
  },

  "Assisted Nordic Hamstring Curl": {
    name: "Assisted Nordic Hamstring Curl",
    aliases: ["Band-Assisted Nordic Curl"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Resistance Band and Anchor",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Glutes", "Calves", "Core"],
    movementPattern: "Knee Flexion",
    analyticsName: "Assisted Nordic Hamstring Curl",
  },

  "Reverse Nordic Curl": {
    name: "Reverse Nordic Curl",
    aliases: ["Reverse Nordic"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Hip Flexors", "Core"],
    movementPattern: "Knee Extension",
    analyticsName: "Reverse Nordic Curl",
  },

  "Sliding Leg Curl": {
    name: "Sliding Leg Curl",
    aliases: ["Floor Slider Hamstring Curl"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Sliders or Towels",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Glutes", "Calves", "Core"],
    movementPattern: "Knee Flexion",
    analyticsName: "Sliding Leg Curl",
  },

  "Swiss Ball Leg Curl": {
    name: "Swiss Ball Leg Curl",
    aliases: ["Stability Ball Hamstring Curl"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Stability Ball",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Glutes", "Calves", "Core"],
    movementPattern: "Knee Flexion",
    analyticsName: "Swiss Ball Leg Curl",
  },

  // ==========================
  // LOWER-BODY MACHINES
  // ==========================

  "Leg Press": {
    name: "Leg Press",
    aliases: ["Machine Leg Press"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Leg Press Machine",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Machine Press",
    analyticsName: "Leg Press",
  },

  "Single-Leg Press": {
    name: "Single-Leg Press",
    aliases: ["One-Leg Leg Press"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Leg Press Machine",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    movementPattern: "Single-Leg Machine Press",
    analyticsName: "Single-Leg Press",
  },

  "Leg Extension": {
    name: "Leg Extension",
    aliases: ["Machine Leg Extension"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Leg Extension Machine",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    movementPattern: "Knee Extension",
    analyticsName: "Leg Extension",
  },

  "Single-Leg Extension": {
    name: "Single-Leg Extension",
    aliases: ["One-Leg Extension"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Leg Extension Machine",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    movementPattern: "Single-Leg Knee Extension",
    analyticsName: "Single-Leg Extension",
  },

  "Lying Leg Curl": {
    name: "Lying Leg Curl",
    aliases: ["Prone Leg Curl"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Leg Curl Machine",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Calves"],
    movementPattern: "Knee Flexion",
    analyticsName: "Lying Leg Curl",
  },

  "Seated Leg Curl": {
    name: "Seated Leg Curl",
    aliases: ["Machine Seated Hamstring Curl"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Leg Curl Machine",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Calves"],
    movementPattern: "Knee Flexion",
    analyticsName: "Seated Leg Curl",
  },

  "Standing Leg Curl": {
    name: "Standing Leg Curl",
    aliases: ["Single-Leg Standing Curl"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Leg Curl Machine",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Calves", "Glutes"],
    movementPattern: "Knee Flexion",
    analyticsName: "Standing Leg Curl",
  },

  "Hip Abduction Machine": {
    name: "Hip Abduction Machine",
    aliases: ["Seated Hip Abduction"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Hip Abduction Machine",
    primaryMuscles: ["Glute Medius", "Hip Abductors"],
    secondaryMuscles: ["Glutes"],
    movementPattern: "Hip Abduction",
    analyticsName: "Hip Abduction Machine",
  },

  "Hip Adduction Machine": {
    name: "Hip Adduction Machine",
    aliases: ["Seated Hip Adduction"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Hip Adduction Machine",
    primaryMuscles: ["Adductors"],
    secondaryMuscles: ["Glutes"],
    movementPattern: "Hip Adduction",
    analyticsName: "Hip Adduction Machine",
  },

  // ==========================
  // CALF AND SHIN EXERCISES
  // ==========================

  "Standing Calf Raise": {
    name: "Standing Calf Raise",
    aliases: ["Calf Raise"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Calves"],
    secondaryMuscles: [],
    movementPattern: "Plantar Flexion",
    analyticsName: "Standing Calf Raise",
  },

  "Single-Leg Calf Raise": {
    name: "Single-Leg Calf Raise",
    aliases: ["One-Leg Calf Raise"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Calves"],
    secondaryMuscles: ["Foot Stabilizers"],
    movementPattern: "Single-Leg Plantar Flexion",
    analyticsName: "Single-Leg Calf Raise",
  },

  "Seated Calf Raise": {
    name: "Seated Calf Raise",
    aliases: ["Machine Seated Calf Raise"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Calf Raise Machine",
    primaryMuscles: ["Soleus"],
    secondaryMuscles: ["Gastrocnemius"],
    movementPattern: "Plantar Flexion",
    analyticsName: "Seated Calf Raise",
  },

  "Donkey Calf Raise": {
    name: "Donkey Calf Raise",
    aliases: [],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight or Machine",
    primaryMuscles: ["Calves"],
    secondaryMuscles: [],
    movementPattern: "Plantar Flexion",
    analyticsName: "Donkey Calf Raise",
  },

  "Leg Press Calf Raise": {
    name: "Leg Press Calf Raise",
    aliases: ["Calf Press"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Leg Press Machine",
    primaryMuscles: ["Calves"],
    secondaryMuscles: [],
    movementPattern: "Plantar Flexion",
    analyticsName: "Leg Press Calf Raise",
  },

  "Tibialis Raise": {
    name: "Tibialis Raise",
    aliases: ["Toe Raise"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Tibialis Anterior"],
    secondaryMuscles: ["Foot Stabilizers"],
    movementPattern: "Dorsiflexion",
    analyticsName: "Tibialis Raise",
  },

  // ==========================
  // PLYOMETRIC AND EXPLOSIVE EXERCISES
  // ==========================

  "Jump Squat": {
    name: "Jump Squat",
    aliases: ["Squat Jump"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Jump",
    analyticsName: "Jump Squat",
  },

  "Box Jump": {
    name: "Box Jump",
    aliases: [],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Plyometric Box",
    primaryMuscles: ["Quadriceps", "Glutes", "Calves"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Jump",
    analyticsName: "Box Jump",
  },

  "Broad Jump": {
    name: "Broad Jump",
    aliases: ["Standing Long Jump"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes", "Quadriceps", "Hamstrings"],
    secondaryMuscles: ["Calves", "Core"],
    movementPattern: "Horizontal Jump",
    analyticsName: "Broad Jump",
  },

  "Tuck Jump": {
    name: "Tuck Jump",
    aliases: ["Knee Tuck Jump"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes", "Hip Flexors"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Jump",
    analyticsName: "Tuck Jump",
  },

  "Depth Jump": {
    name: "Depth Jump",
    aliases: ["Drop Jump"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Plyometric Box",
    primaryMuscles: ["Quadriceps", "Glutes", "Calves"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Reactive Jump",
    analyticsName: "Depth Jump",
  },

  "Lateral Bound": {
    name: "Lateral Bound",
    aliases: ["Skater Bound"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Adductors", "Hamstrings", "Calves", "Core"],
    movementPattern: "Lateral Jump",
    analyticsName: "Lateral Bound",
  },

  "Skater Jump": {
    name: "Skater Jump",
    aliases: ["Speed Skater Jump"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Lateral Jump",
    analyticsName: "Skater Jump",
  },

  "Single-Leg Hop": {
    name: "Single-Leg Hop",
    aliases: ["One-Leg Hop"],
    category: "lowerBody",
    type: "dynamic",
    exerciseType: "repetition",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Calves", "Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Single-Leg Jump",
    analyticsName: "Single-Leg Hop",
  },

  // ==========================
  // LOWER-BODY HOLD EXERCISES
  // ==========================

  "Wall Sit": {
    name: "Wall Sit",
    aliases: ["Wall Squat Hold"],
    category: "lowerBody",
    type: "hold",
    exerciseType: "hold",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Wall",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Calves"],
    movementPattern: "Squat Hold",
    analyticsName: "Wall Sit",
  },

  "Squat Hold": {
    name: "Squat Hold",
    aliases: ["Bottom Squat Hold"],
    category: "lowerBody",
    type: "hold",
    exerciseType: "hold",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Squat Hold",
    analyticsName: "Squat Hold",
  },

  "Split Squat Hold": {
    name: "Split Squat Hold",
    aliases: ["Static Lunge Hold"],
    category: "lowerBody",
    type: "hold",
    exerciseType: "hold",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Lunge Hold",
    analyticsName: "Split Squat Hold",
  },

  "Bulgarian Split Squat Hold": {
    name: "Bulgarian Split Squat Hold",
    aliases: ["Rear Foot Elevated Split Squat Hold"],
    category: "lowerBody",
    type: "hold",
    exerciseType: "hold",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bench",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Split Squat Hold",
    analyticsName: "Bulgarian Split Squat Hold",
  },

  "Glute Bridge Hold": {
    name: "Glute Bridge Hold",
    aliases: ["Static Glute Bridge"],
    category: "lowerBody",
    type: "hold",
    exerciseType: "hold",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Hip Extension Hold",
    analyticsName: "Glute Bridge Hold",
  },

  "Single-Leg Glute Bridge Hold": {
    name: "Single-Leg Glute Bridge Hold",
    aliases: ["One-Leg Glute Bridge Hold"],
    category: "lowerBody",
    type: "hold",
    exerciseType: "hold",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Single-Leg Hip Extension Hold",
    analyticsName: "Single-Leg Glute Bridge Hold",
  },

  "Calf Raise Hold": {
    name: "Calf Raise Hold",
    aliases: ["Top Calf Raise Hold"],
    category: "lowerBody",
    type: "hold",
    exerciseType: "hold",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Calves"],
    secondaryMuscles: ["Foot Stabilizers"],
    movementPattern: "Plantar Flexion Hold",
    analyticsName: "Calf Raise Hold",
  },

  // ==========================
 // CORE
 // ==========================

 // ==========================
 // BASIC ABDOMINAL EXERCISES
 // ==========================

 "Crunch": {
  name: "Crunch",
  aliases: ["Ab Crunch"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Rectus Abdominis"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Spinal Flexion",
  analyticsName: "Crunch",
 },

 "Reverse Crunch": {
  name: "Reverse Crunch",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Lower Abs"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Hip Flexion",
  analyticsName: "Reverse Crunch",
 },

 "Toe Touch": {
  name: "Toe Touch",
  aliases: ["Toe Touch Crunch"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Upper Abs"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Spinal Flexion",
  analyticsName: "Toe Touch",
 },

 "Sit Up": {
  name: "Sit Up",
  aliases: ["Abdominal Sit Up"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Rectus Abdominis"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Spinal Flexion",
  analyticsName: "Sit Up",
 },

 "Bicycle Crunch": {
  name: "Bicycle Crunch",
  aliases: ["Bicycle"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Rectus Abdominis", "Obliques"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Rotation",
  analyticsName: "Bicycle Crunch",
 },

 "Cross Crunch": {
  name: "Cross Crunch",
  aliases: ["Cross Body Crunch"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Obliques"],
  secondaryMuscles: ["Rectus Abdominis"],
  movementPattern: "Rotation",
  analyticsName: "Cross Crunch",
 },

 "Heel Touch": {
  name: "Heel Touch",
  aliases: ["Heel Tap"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Obliques"],
  secondaryMuscles: ["Rectus Abdominis"],
  movementPattern: "Lateral Flexion",
  analyticsName: "Heel Touch",
 },

 // ==========================
 // LEG RAISE VARIATIONS
 // ==========================

"Leg Raise": {
  name: "Leg Raise",
  aliases: ["Lying Leg Raise"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Lower Abs"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Hip Flexion",
  analyticsName: "Leg Raise",
},

"Hanging Knee Raise": {
  name: "Hanging Knee Raise",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 2,
  difficulty: DIFFICULTY.TIER_2,
  equipment: "Pull-up Bar",
  primaryMuscles: ["Lower Abs"],
  secondaryMuscles: ["Hip Flexors", "Grip"],
  movementPattern: "Hanging",
  analyticsName: "Hanging Knee Raise",
},

"Hanging Leg Raise": {
  name: "Hanging Leg Raise",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 2,
  difficulty: DIFFICULTY.TIER_2,
  equipment: "Pull-up Bar",
  primaryMuscles: ["Lower Abs"],
  secondaryMuscles: ["Hip Flexors", "Grip"],
  movementPattern: "Hanging",
  analyticsName: "Hanging Leg Raise",
},

"Toes to Bar": {
  name: "Toes to Bar",
  aliases: ["Toes-to-Bar"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 3,
  difficulty: DIFFICULTY.TIER_3,
  equipment: "Pull-up Bar",
  primaryMuscles: ["Rectus Abdominis"],
  secondaryMuscles: ["Hip Flexors", "Lats", "Grip"],
  movementPattern: "Hanging",
  analyticsName: "Toes to Bar",
},

"Windshield Wipers": {
  name: "Windshield Wipers",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 3,
  difficulty: DIFFICULTY.TIER_3,
  equipment: "Pull-up Bar",
  primaryMuscles: ["Obliques"],
  secondaryMuscles: ["Rectus Abdominis", "Grip"],
  movementPattern: "Rotation",
  analyticsName: "Windshield Wipers",
},

"Dragon Flag": {
  name: "Dragon Flag",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 4,
  difficulty: DIFFICULTY.TIER_4,
  equipment: "Bench",
  primaryMuscles: ["Rectus Abdominis"],
  secondaryMuscles: ["Lats", "Shoulders"],
  movementPattern: "Anti-Extension",
  analyticsName: "Dragon Flag",
},

// ==========================
// ROTATION
// ==========================

"Russian Twist": {
  name: "Russian Twist",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Obliques"],
  secondaryMuscles: ["Rectus Abdominis"],
  movementPattern: "Rotation",
  analyticsName: "Russian Twist",
},

"Medicine Ball Twist": {
  name: "Medicine Ball Twist",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Medicine Ball",
  primaryMuscles: ["Obliques"],
  secondaryMuscles: ["Rectus Abdominis"],
  movementPattern: "Rotation",
  analyticsName: "Medicine Ball Twist",
},

"Cable Wood Chop": {
  name: "Cable Wood Chop",
  aliases: ["Wood Chop"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Cable",
  primaryMuscles: ["Obliques"],
  secondaryMuscles: ["Rectus Abdominis"],
  movementPattern: "Rotation",
  analyticsName: "Cable Wood Chop",
},

"Pallof Press": {
  name: "Pallof Press",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 2,
  difficulty: DIFFICULTY.TIER_2,
  equipment: "Cable",
  primaryMuscles: ["Transverse Abdominis"],
  secondaryMuscles: ["Obliques"],
  movementPattern: "Anti-Rotation",
  analyticsName: "Pallof Press",
},

// ==========================
// STABILITY
// ==========================

"Dead Bug": {
  name: "Dead Bug",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Transverse Abdominis"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Stability",
  analyticsName: "Dead Bug",
},

"Bird Dog": {
  name: "Bird Dog",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Core"],
  secondaryMuscles: ["Glutes", "Lower Back"],
  movementPattern: "Stability",
  analyticsName: "Bird Dog",
},

"Mountain Climber": {
  name: "Mountain Climber",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Core"],
  secondaryMuscles: ["Shoulders", "Hip Flexors"],
  movementPattern: "Dynamic Stability",
  analyticsName: "Mountain Climber",
},

"Cross Body Mountain Climber": {
  name: "Cross Body Mountain Climber",
  aliases: [],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 2,
  difficulty: DIFFICULTY.TIER_2,
  equipment: "Bodyweight",
  primaryMuscles: ["Obliques"],
  secondaryMuscles: ["Core", "Shoulders"],
  movementPattern: "Rotation",
  analyticsName: "Cross Body Mountain Climber",
},

"Ab Wheel Rollout": {
  name: "Ab Wheel Rollout",
  aliases: ["Wheel Rollout"],
  category: "core",
  type: "dynamic",
  exerciseType: "repetition",
  tier: 2,
  difficulty: DIFFICULTY.TIER_2,
  equipment: "Ab Wheel",
  primaryMuscles: ["Rectus Abdominis"],
  secondaryMuscles: ["Lats", "Shoulders"],
  movementPattern: "Anti-Extension",
  analyticsName: "Ab Wheel Rollout",
},

// ==========================
// HOLDS
// ==========================

Plank: {
  name: "Plank",
  aliases: ["Front Plank"],
  category: "core",
  type: "hold",
  exerciseType: "hold",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Core"],
  secondaryMuscles: ["Shoulders", "Glutes"],
  movementPattern: "Stability Hold",
  analyticsName: "Plank",
},

"Side Plank": {
  name: "Side Plank",
  aliases: [],
  category: "core",
  type: "hold",
  exerciseType: "hold",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Obliques"],
  secondaryMuscles: ["Glute Medius"],
  movementPattern: "Lateral Stability",
  analyticsName: "Side Plank",
},

"Reverse Plank": {
  name: "Reverse Plank",
  aliases: [],
  category: "core",
  type: "hold",
  exerciseType: "hold",
  tier: 1,
 difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Posterior Chain"],
  secondaryMuscles: ["Core"],
  movementPattern: "Posterior Hold",
  analyticsName: "Reverse Plank",
},

"Hollow Hold": {
  name: "Hollow Hold",
  aliases: ["Hollow Body Hold"],
  category: "core",
  type: "hold",
  exerciseType: "hold",
  tier: 2,
  difficulty: DIFFICULTY.TIER_2,
  equipment: "Bodyweight",
  primaryMuscles: ["Rectus Abdominis"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Anti-Extension",
  analyticsName: "Hollow Hold",
},

"Superman Hold": {
  name: "Superman Hold",
  aliases: [],
  category: "core",
  type: "hold",
  exerciseType: "hold",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Lower Back"],
  secondaryMuscles: ["Glutes"],
  movementPattern: "Posterior Hold",
  analyticsName: "Superman Hold",
},

"L-Sit": {
  name: "L-Sit",
  aliases: [],
  category: "core",
  type: "hold",
  exerciseType: "hold",
  tier: 3,
  difficulty: DIFFICULTY.TIER_3,
  equipment: "Parallettes",
  primaryMuscles: ["Core"],
  secondaryMuscles: ["Hip Flexors", "Shoulders", "Triceps"],
  movementPattern: "Gymnastics Hold",
  analyticsName: "L-Sit",
},

"Tuck L-Sit": {
  name: "Tuck L-Sit",
  aliases: [],
  category: "core",
  type: "hold",
  exerciseType: "hold",
  tier: 2,
  difficulty: DIFFICULTY.TIER_2,
  equipment: "Parallettes",
  primaryMuscles: ["Core"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Gymnastics Hold",
  analyticsName: "Tuck L-Sit",
},

"V-Sit": {
  name: "V-Sit",
  aliases: [],
  category: "core",
  type: "hold",
  exerciseType: "hold",
  tier: 4,
  difficulty: DIFFICULTY.TIER_4,
  equipment: "Parallettes",
  primaryMuscles: ["Core"],
  secondaryMuscles: ["Hip Flexors", "Shoulders"],
  movementPattern: "Gymnastics Hold",
  analyticsName: "V-Sit",
},

"Boat Pose": {
  name: "Boat Pose",
  aliases: ["Navasana"],
  category: "core",
  type: "hold",
  exerciseType: "hold",
  tier: 1,
  difficulty: DIFFICULTY.TIER_1,
  equipment: "Bodyweight",
  primaryMuscles: ["Core"],
  secondaryMuscles: ["Hip Flexors"],
  movementPattern: "Static Hold",
  analyticsName: "Boat Pose",
 },
};