import { DIFFICULTY } from "./difficulty";

export const EXERCISE_LIBRARY = {
  // ==========================
  // UPPER BODY
  // ==========================

  "Push Up": {
    name: "Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    movementPattern: "Horizontal Push",
    analyticsName: "Push Up",
  },

  "Bench Press": {
    name: "Bench Press",
    aliases: ["Flat Bench"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    movementPattern: "Horizontal Push",
    analyticsName: "Bench Press",
  },

  "Incline Bench Press": {
    name: "Incline Bench Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Front Delts", "Triceps"],
    movementPattern: "Incline Push",
    analyticsName: "Incline Bench Press",
  },

  "Chest Fly": {
    name: "Chest Fly",
    aliases: ["Dumbbell Fly"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "Chest Fly",
  },

  "Pull Up": {
    name: "Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Upper Back"],
    movementPattern: "Vertical Pull",
    analyticsName: "Pull Up",
  },

  "Chin Up": {
    name: "Chin Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Lats"],
    movementPattern: "Vertical Pull",
    analyticsName: "Chin Up",
  },

  "Lat Pulldown": {
    name: "Lat Pulldown",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Lat Pulldown",
  },

  "Bent Over Row": {
    name: "Bent Over Row",
    aliases: ["Barbell Row"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Lats", "Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Bent Over Row",
  },

  "Seated Cable Row": {
    name: "Seated Cable Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Lats", "Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Seated Cable Row",
  },

  Dip: {
    name: "Dip",
    aliases: ["Parallel Bar Dip"],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dip Bars",
    primaryMuscles: ["Chest", "Triceps"],
    secondaryMuscles: ["Front Delts"],
    movementPattern: "Vertical Push",
    analyticsName: "Dip",
  },

  "Shoulder Press": {
    name: "Shoulder Press",
    aliases: ["Overhead Press"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Shoulder Press",
  },

  "Lateral Raise": {
    name: "Lateral Raise",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Side Delts"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Lateral Raise",
  },

  "Bicep Curl": {
    name: "Bicep Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Bicep Curl",
  },

  "Tricep Pushdown": {
    name: "Tricep Pushdown",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Tricep Pushdown",
  },

  "Muscle Up": {
    name: "Muscle Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats", "Chest"],
    secondaryMuscles: ["Shoulders", "Biceps", "Triceps"],
    movementPattern: "Explosive Pull",
    analyticsName: "Muscle Up",
  },

  "Arnold Press": {
    name: "Arnold Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dumbbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Arnold Press",
  },

  "Australian Row": {
    name: "Australian Row",
    aliases: ["Bodyweight Row", "Inverted Row"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bar",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Australian Row",
  },

  "Cable Curl": {
    name: "Cable Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Cable Curl",
  },

  "Cable Fly": {
    name: "Cable Fly",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "Cable Fly",
  },

  "Cable Row": {
    name: "Cable Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Cable Row",
  },

  "Chest Dip": {
    name: "Chest Dip",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dip Bars",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Chest Dip",
  },

  "Chest Press Machine": {
    name: "Chest Press Machine",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Chest Press Machine",
  },

  "Chest Supported Row": {
    name: "Chest Supported Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Chest Supported Row",
  },

  "Close Grip Bench Press": {
    name: "Close Grip Bench Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Barbell",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Chest"],
    movementPattern: "Horizontal Push",
    analyticsName: "Close Grip Bench Press",
  },

  "Close Grip Pull Up": {
    name: "Close Grip Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Close Grip Pull Up",
  },

  "Concentration Curl": {
    name: "Concentration Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Concentration Curl",
  },

  "Decline Bench Press": {
    name: "Decline Bench Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Lower Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Decline Bench Press",
  },

  "Decline Push Up": {
    name: "Decline Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Decline Push Up",
  },

  "Diamond Push Up": {
    name: "Diamond Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Chest"],
    movementPattern: "Horizontal Push",
    analyticsName: "Diamond Push Up",
  },

  "Dumbbell Bench Press": {
    name: "Dumbbell Bench Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Dumbbell Bench Press",
  },

  "Dumbbell Curl": {
    name: "Dumbbell Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Dumbbell Curl",
  },

  "Dumbbell Pullover": {
    name: "Dumbbell Pullover",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dumbbell",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Chest"],
    movementPattern: "Pull",
    analyticsName: "Dumbbell Pullover",
  },

  "Dumbbell Row": {
    name: "Dumbbell Row",
    aliases: ["One Arm Row"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Dumbbell Row",
  },

  "Dumbbell Shoulder Press": {
    name: "Dumbbell Shoulder Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Dumbbell Shoulder Press",
  },

  "EZ Bar Curl": {
    name: "EZ Bar Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "EZ Bar",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "EZ Bar Curl",
  },

  "Face Pull": {
    name: "Face Pull",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Upper Back"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Face Pull",
  },

  "Farmer Carry": {
    name: "Farmer Carry",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Dumbbell",
    primaryMuscles: ["Forearms"],
    secondaryMuscles: ["Traps", "Core"],
    movementPattern: "Carry",
    analyticsName: "Farmer Carry",
  },

  "Flat Bench Dumbbell Fly": {
    name: "Flat Bench Dumbbell Fly",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "Flat Bench Dumbbell Fly",
  },

  "Front Raise": {
    name: "Front Raise",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Front Delts"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Front Raise",
  },

  "Hammer Curl": {
    name: "Hammer Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    movementPattern: "Isolation",
    analyticsName: "Hammer Curl",
  },

  "Handstand Push Up": {
    name: "Handstand Push Up",
    aliases: ["HSPU"],
    category: "upperBody",
    type: "dynamic",
    tier: 4,
    difficulty: DIFFICULTY.TIER_4,
    equipment: "Bodyweight",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Handstand Push Up",
  },

  "High Cable Fly": {
    name: "High Cable Fly",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "High Cable Fly",
  },

  "Hindu Push Up": {
    name: "Hindu Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Hindu Push Up",
  },

  "Incline Dumbbell Press": {
    name: "Incline Dumbbell Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Front Delts"],
    movementPattern: "Incline Push",
    analyticsName: "Incline Dumbbell Press",
  },

  "Incline Push Up": {
    name: "Incline Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Horizontal Push",
    analyticsName: "Incline Push Up",
  },

  "Machine Shoulder Press": {
    name: "Machine Shoulder Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Machine Shoulder Press",
  },

  "Neutral Grip Pull Up": {
    name: "Neutral Grip Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Neutral Grip Pull Up",
  },

  "One Arm Pull Up": {
    name: "One Arm Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 4,
    difficulty: DIFFICULTY.TIER_4,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "One Arm Pull Up",
  },

  "One Arm Push Up": {
    name: "One Arm Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 4,
    difficulty: DIFFICULTY.TIER_4,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Core"],
    movementPattern: "Horizontal Push",
    analyticsName: "One Arm Push Up",
  },

  "Overhead Tricep Extension": {
    name: "Overhead Tricep Extension",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Overhead Tricep Extension",
  },

  "Pec Deck": {
    name: "Pec Deck",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    movementPattern: "Fly",
    analyticsName: "Pec Deck",
  },

  "Pike Push Up": {
    name: "Pike Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Bodyweight",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Pike Push Up",
  },

  "Preacher Curl": {
    name: "Preacher Curl",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "EZ Bar",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Preacher Curl",
  },

  "Pseudo Planche Push Up": {
    name: "Pseudo Planche Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Core"],
    movementPattern: "Horizontal Push",
    analyticsName: "Pseudo Planche Push Up",
  },

    "Rear Delt Fly": {
    name: "Rear Delt Fly",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Upper Back"],
    movementPattern: "Isolation",
    analyticsName: "Rear Delt Fly",
  },

  "Resistance Band Row": {
    name: "Resistance Band Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Resistance Band",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Resistance Band Row",
  },

  "Ring Dip": {
    name: "Ring Dip",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Gymnastic Rings",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Shoulders"],
    movementPattern: "Vertical Push",
    analyticsName: "Ring Dip",
  },

  "Ring Push Up": {
    name: "Ring Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Gymnastic Rings",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Core"],
    movementPattern: "Horizontal Push",
    analyticsName: "Ring Push Up",
  },

  "Ring Row": {
    name: "Ring Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Gymnastic Rings",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "Ring Row",
  },

  "Seated Dumbbell Press": {
    name: "Seated Dumbbell Press",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Seated Dumbbell Press",
  },

  "Shoulder Press Machine": {
    name: "Shoulder Press Machine",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Machine",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Shoulder Press Machine",
  },

  "Shrugs": {
    name: "Shrugs",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Dumbbell",
    primaryMuscles: ["Traps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Shrugs",
  },

  "Skull Crusher": {
    name: "Skull Crusher",
    aliases: ["Lying Tricep Extension"],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "EZ Bar",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Skull Crusher",
  },

  "Straight Arm Pulldown": {
    name: "Straight Arm Pulldown",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Cable",
    primaryMuscles: ["Lats"],
    secondaryMuscles: [],
    movementPattern: "Isolation",
    analyticsName: "Straight Arm Pulldown",
  },

  "T-Bar Row": {
    name: "T-Bar Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Barbell",
    primaryMuscles: ["Upper Back"],
    secondaryMuscles: ["Lats", "Biceps"],
    movementPattern: "Horizontal Pull",
    analyticsName: "T-Bar Row",
  },

  "Typewriter Pull Up": {
    name: "Typewriter Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 4,
    difficulty: DIFFICULTY.TIER_4,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Core"],
    movementPattern: "Vertical Pull",
    analyticsName: "Typewriter Pull Up",
  },

  "Upright Row": {
    name: "Upright Row",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Barbell",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Traps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Upright Row",
  },

  "Weighted Dip": {
    name: "Weighted Dip",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Dip Belt",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    movementPattern: "Vertical Push",
    analyticsName: "Weighted Dip",
  },

  "Weighted Pull Up": {
    name: "Weighted Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 3,
    difficulty: DIFFICULTY.TIER_3,
    equipment: "Dip Belt",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    movementPattern: "Vertical Pull",
    analyticsName: "Weighted Pull Up",
  },

  "Wide Grip Pull Up": {
    name: "Wide Grip Pull Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 2,
    difficulty: DIFFICULTY.TIER_2,
    equipment: "Pull-up Bar",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Upper Back"],
    movementPattern: "Vertical Pull",
    analyticsName: "Wide Grip Pull Up",
  },

  "Wide Push Up": {
    name: "Wide Push Up",
    aliases: [],
    category: "upperBody",
    type: "dynamic",
    tier: 1,
    difficulty: DIFFICULTY.TIER_1,
    equipment: "Bodyweight",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders"],
    movementPattern: "Horizontal Push",
    analyticsName: "Wide Push Up",
  },
};
