export const SKILL_AREA_OPTIONS = [
  "Academic",
  "Communication",
  "Creative",
  "Fitness",
  "Language",
  "Music",
  "Personal Development",
  "Practical",
  "Professional",
  "Technical",
  "Other",
];

export const SKILL_TAG_OPTIONS = [
  "Art",
  "Balance",
  "Business",
  "Calisthenics",
  "Camera",
  "Coding",
  "Communication",
  "Confidence",
  "Creativity",
  "Design",
  "Digital",
  "Education",
  "Editing",
  "Finance",
  "Food",
  "Frontend",
  "Backend",
  "Instrument",
  "Language",
  "Listening",
  "Management",
  "Money",
  "Music",
  "Observation",
  "Presentation",
  "Problem Solving",
  "Professional",
  "Psychology",
  "Reading",
  "Software Development",
  "Speaking",
  "Strategy",
  "Strength",
  "Technology",
  "Video",
  "Writing",
];