export const WORKOUT_CATEGORY_IDS = ["upperBody", "lowerBody", "core"];

export const WORKOUT_CATEGORIES = new Set(WORKOUT_CATEGORY_IDS);

export const CATEGORIES = [
  {
    id: "water",
    name: "Water",
    emoji: "💧",
    description: "Track the water you drink throughout the day.",
    fields: [
      {
        id: "amount",
        label: "Water",
        type: "number",
        placeholder: "500",
        required: true,
        min: 1,
        step: 1,
      },
    ],
    scoreField: "amount",
    unit: "ml",
  },
  {
    id: "fruit",
    name: "Fruit",
    emoji: "🍎",
    description: "Record whole-fruit servings that support your nutrition goals.",
    fields: [
      {
        id: "fruitType",
        label: "Fruit",
        type: "select",
        required: true,
      },
      {
        id: "servings",
        label: "Servings",
        type: "number",
        placeholder: "Number of servings",
        required: true,
        min: 1,
        step: 1,
      },
    ],
    scoreField: "servings",
    unit: "servings",
  },
  {
    id: "reading",
    name: "Reading",
    emoji: "📚",
    description: "Build knowledge through focused reading sessions.",
    fields: [
      { id: "hours", label: "Hours", type: "number", min: 0, step: 1 },
      {
        id: "minutes",
        label: "Minutes",
        type: "number",
        min: 0,
        max: 59,
        step: 1,
      },
      {
        id: "seconds",
        label: "Seconds",
        type: "number",
        min: 0,
        max: 59,
        step: 1,
      },
      {
        id: "title",
        label: "Book",
        type: "text",
        placeholder: "What book did you read?",
        required: true,
      },
      {
        id: "completed",
        label: "Book Completed",
        type: "select",
        required: true,
      },
      {
        id: "reflection",
        label: "Reflection",
        type: "text",
        placeholder: "Optional: What did you learn?",
      },
    ],
    scoreField: "totalMinutes",
    unit: "min",
  },
  {
    id: "running",
    name: "Running",
    emoji: "🏃",
    description: "Log distance, duration and pace. Running also contributes to Cardio.",
    fields: [
      {
        id: "distance",
        label: "Distance",
        type: "number",
        placeholder: "Distance in kilometres",
        required: true,
        min: 0.01,
        step: 0.01,
      },
      { id: "hours", label: "Hours", type: "number", min: 0, step: 1 },
      {
        id: "minutes",
        label: "Minutes",
        type: "number",
        min: 0,
        max: 59,
        step: 1,
      },
      {
        id: "seconds",
        label: "Seconds",
        type: "number",
        min: 0,
        max: 59,
        step: 1,
      },
    ],
    scoreField: "distance",
    unit: "km",
    statisticsContributions: [
      {
        categoryId: "cardio",
        field: "totalMinutes",
      },
    ],
  },
  {
    id: "upperBody",
    name: "Upper Body",
    emoji: "💪",
    description: "Train pushing, pulling and upper-body strength.",
    unit: "Effective Repetitions",
  },
  {
    id: "lowerBody",
    name: "Lower Body",
    emoji: "🦵",
    description: "Build lower-body strength, balance and power.",
    unit: "Effective Repetitions",
  },
  {
    id: "core",
    name: "Core",
    emoji: "🔥",
    description: "Strengthen your trunk, stability and control.",
    unit: "Effective Repetitions",
  },
  {
    id: "cardio",
    name: "Cardio",
    emoji: "❤️",
    description: "Record conditioning work and cardiovascular activity.",
    fields: [
      {
        id: "activity",
        label: "Activity",
        type: "select",
        required: true,
      },
      { id: "hours", label: "Hours", type: "number", min: 0, step: 1 },
      {
        id: "minutes",
        label: "Minutes",
        type: "number",
        min: 0,
        max: 59,
        step: 1,
      },
      {
        id: "seconds",
        label: "Seconds",
        type: "number",
        min: 0,
        max: 59,
        step: 1,
      },
    ],
    scoreField: "totalMinutes",
    unit: "min",
  },
  {
    id: "skill",
    name: "Skill Development",
    shortName: "Skills",
    emoji: "🎯",
    description: "Practise a useful ability with deliberate focus.",
    fields: [
      {
        id: "skill",
        label: "Skill",
        type: "select",
        required: true,
      },
      { id: "hours", label: "Hours", type: "number", min: 0, step: 1 },
      {
        id: "minutes",
        label: "Minutes",
        type: "number",
        min: 0,
        max: 59,
        step: 1,
      },
      {
        id: "seconds",
        label: "Seconds",
        type: "number",
        min: 0,
        max: 59,
        step: 1,
      },
    ],
    scoreField: "totalMinutes",
    unit: "min",
  },
  {
    id: "steps",
    name: "Steps",
    emoji: "👣",
    description: "Track your daily movement and walking volume.",
    fields: [
      {
        id: "steps",
        label: "Steps",
        type: "number",
        placeholder: "Number of steps",
        required: true,
        min: 1,
        step: 1,
      },
    ],
    scoreField: "steps",
    unit: "steps",
  },
];

export const CATEGORY_MAP = new Map(
  CATEGORIES.map((category) => [category.id, category]),
);
