export const MBTI_TYPES = Object.freeze([
  "ISTJ", "ISFJ", "INFJ", "INTJ",
  "ISTP", "ISFP", "INFP", "INTP",
  "ESTP", "ESFP", "ENFP", "ENTP",
  "ESTJ", "ESFJ", "ENFJ", "ENTJ",
]);

const profiles = [
  {
    type: "ISTJ",
    title: "The Sentinel",
    symbol: "🛡️",
    primary: "#52647a",
    secondary: "#e5ebf2",
    tagline: "Steady systems, quiet discipline, dependable follow-through.",
    strengths: ["Consistency", "Practical planning", "Reliable follow-through"],
    watchouts: ["Rigid routines", "Under-celebrating progress", "Difficulty adjusting when plans change"],
    thrive: [
      "Use fixed training and logging times so consistency becomes automatic.",
      "Track measurable progress in Running, workouts and Reading rather than chasing novelty.",
      "When a week goes off-plan, define the smallest acceptable fallback instead of abandoning the plan.",
    ],
    connections: ["ESFP", "ESTP", "ISFJ"],
  },
  {
    type: "ISFJ",
    title: "The Guardian",
    symbol: "🕯️",
    primary: "#477a68",
    secondary: "#e1f1eb",
    tagline: "Loyal effort, thoughtful support, strength through dependable habits.",
    strengths: ["Patience", "Supportiveness", "Attention to practical detail"],
    watchouts: ["Putting others first too often", "Avoiding necessary change", "Taking setbacks personally"],
    thrive: [
      "Build routines around care for your future self: water, recovery, movement and sleep-friendly habits.",
      "Use a training partner or House commitment when accountability helps you show up.",
      "Treat missed goals as information, then calmly restart the next available action.",
    ],
    connections: ["ENTP", "ESTP", "ISTJ"],
  },
  {
    type: "INFJ",
    title: "The Seer",
    symbol: "🔮",
    primary: "#72588d",
    secondary: "#eee5f6",
    tagline: "Purpose-led growth, reflection, and a strong sense of what progress means.",
    strengths: ["Long-term purpose", "Reflection", "Empathy"],
    watchouts: ["Perfectionism", "Overthinking", "Burning out while chasing meaningful goals"],
    thrive: [
      "Connect each category to a personal reason so routine actions still feel meaningful.",
      "Use Journal and Reading reflection to turn progress into lessons rather than only numbers.",
      "Set a minimum viable training day so perfectionism cannot turn one imperfect day into zero progress.",
    ],
    connections: ["ENTP", "ENFP", "ISFJ"],
  },
  {
    type: "INTJ",
    title: "The Strategist",
    symbol: "♟️",
    primary: "#3f526d",
    secondary: "#e1e7ef",
    tagline: "Independent planning, long-range thinking, and deliberate improvement.",
    strengths: ["Strategy", "Self-direction", "Systems thinking"],
    watchouts: ["Over-optimising", "Impatience with slow progress", "Ignoring simple habits while designing better systems"],
    thrive: [
      "Treat goals like a system: define inputs, review trends, then change one variable at a time.",
      "Use Analytics to test whether your plan is actually working rather than relying on intuition alone.",
      "Keep basic categories simple; not every habit needs a sophisticated optimisation plan.",
    ],
    connections: ["ENFP", "ENTP", "ISTJ"],
  },
  {
    type: "ISTP",
    title: "The Tactician",
    symbol: "🧭",
    primary: "#556d62",
    secondary: "#e4ece8",
    tagline: "Hands-on problem solving, adaptability, and calm action under pressure.",
    strengths: ["Adaptability", "Practical problem solving", "Calm execution"],
    watchouts: ["Boredom with repetition", "Inconsistent long-term structure", "Waiting for motivation"],
    thrive: [
      "Use flexible training options that still satisfy the same category goal.",
      "Turn workouts and Skill Development into experiments with clear measurable outcomes.",
      "Keep a short default routine for days when freedom and variety become indecision.",
    ],
    connections: ["ENFJ", "ESFJ", "ESTP"],
  },
  {
    type: "ISFP",
    title: "The Artisan",
    symbol: "🌿",
    primary: "#68804f",
    secondary: "#edf3e6",
    tagline: "Personal expression, grounded action, and growth that feels authentic.",
    strengths: ["Adaptability", "Present-moment awareness", "Personal values"],
    watchouts: ["Avoiding rigid plans", "Losing momentum without immediate meaning", "Under-planning"],
    thrive: [
      "Choose movement and Skill activities that feel personally engaging instead of forcing one ideal routine.",
      "Use visual progress and personal records to make improvement tangible.",
      "Keep weekly goals visible so spontaneity still has a reliable direction.",
    ],
    connections: ["ENTJ", "ENFJ", "ESFP"],
  },
  {
    type: "INFP",
    title: "The Dreamkeeper",
    symbol: "🌙",
    primary: "#6d5f91",
    secondary: "#ece8f7",
    tagline: "Values, imagination, and meaningful progress built from the inside out.",
    strengths: ["Personal meaning", "Creativity", "Empathy"],
    watchouts: ["Inconsistent structure", "All-or-nothing motivation", "Discouragement when reality misses the ideal"],
    thrive: [
      "Write down why each goal matters to you before focusing on the score attached to it.",
      "Use Reading, Journal and Skill Development as fuel for identity-based growth.",
      "Create gentle minimums for low-energy days so your values survive imperfect motivation.",
    ],
    connections: ["ENTJ", "ENFJ", "ENFP"],
  },
  {
    type: "INTP",
    title: "The Scholar",
    symbol: "🧠",
    primary: "#4f6088",
    secondary: "#e5e9f5",
    tagline: "Curiosity, analysis, and progress through understanding how things work.",
    strengths: ["Analysis", "Curiosity", "Independent learning"],
    watchouts: ["Analysis paralysis", "Inconsistent execution", "Losing interest after understanding the system"],
    thrive: [
      "Use Analytics and personal records as experiments: form a hypothesis, test it, review it.",
      "Pair Reading and Skill Development with a concrete output or practice target.",
      "Set a start rule such as five minutes of action before allowing yourself to redesign the plan.",
    ],
    connections: ["ENTJ", "ENFJ", "ENTP"],
  },
  {
    type: "ESTP",
    title: "The Vanguard",
    symbol: "⚔️",
    primary: "#9a5a37",
    secondary: "#f6e8df",
    tagline: "Action first, fast feedback, and energy from real-world challenge.",
    strengths: ["Decisive action", "Adaptability", "Competitive energy"],
    watchouts: ["Impulsiveness", "Skipping recovery", "Boredom with slow-building habits"],
    thrive: [
      "Use short competitive targets, personal records and House goals to create immediate stakes.",
      "Keep Running and workouts varied while preserving the underlying weekly minimums.",
      "Schedule recovery with the same seriousness as high-intensity effort.",
    ],
    connections: ["ISFJ", "ISTJ", "ISTP"],
  },
  {
    type: "ESFP",
    title: "The Spark",
    symbol: "✨",
    primary: "#a55b68",
    secondary: "#f8e5e9",
    tagline: "Energy, connection, and momentum that grows when progress feels alive.",
    strengths: ["Enthusiasm", "Adaptability", "Social encouragement"],
    watchouts: ["Distraction", "Inconsistent long-term planning", "Chasing excitement over recovery"],
    thrive: [
      "Use House participation and shared challenges to make consistency social and energising.",
      "Rotate activities inside Cardio and Skill Development so the routine stays engaging.",
      "Keep one simple weekly planning ritual to protect long-term goals from short-term excitement.",
    ],
    connections: ["ISTJ", "ISFJ", "ENFP"],
  },
  {
    type: "ENFP",
    title: "The Pathfinder",
    symbol: "🦋",
    primary: "#8d5b9f",
    secondary: "#f0e6f4",
    tagline: "Possibility, enthusiasm, and growth powered by meaningful variety.",
    strengths: ["Motivation", "Creativity", "Connecting ideas and people"],
    watchouts: ["Too many goals at once", "Routine fatigue", "Strong starts followed by scattered follow-through"],
    thrive: [
      "Choose a small number of priority categories each week while keeping the rest at maintenance level.",
      "Use Skill Development and varied Cardio to satisfy curiosity without constantly replacing the whole plan.",
      "Share goals with supportive people when external energy helps sustain follow-through.",
    ],
    connections: ["INTJ", "INFJ", "INFP"],
  },
  {
    type: "ENTP",
    title: "The Challenger",
    symbol: "🐉",
    primary: "#6d5794",
    secondary: "#ebe6f4",
    tagline: "Experimentation, challenge, and progress through testing better possibilities.",
    strengths: ["Inventiveness", "Adaptability", "Strategic debate"],
    watchouts: ["Changing plans too quickly", "Boredom with maintenance", "Arguing with a system instead of using it"],
    thrive: [
      "Treat training blocks as experiments with a fixed review date instead of changing direction every few days.",
      "Use personal records and Power Plays as puzzles that reward creative strategy without changing the rules.",
      "Protect boring essentials such as Water, Steps and recovery with automatic routines.",
    ],
    connections: ["INFJ", "INTJ", "ISFJ"],
  },
  {
    type: "ESTJ",
    title: "The Marshal",
    symbol: "🦅",
    primary: "#7a6047",
    secondary: "#f0e8df",
    tagline: "Structure, responsibility, and visible progress through decisive organisation.",
    strengths: ["Organisation", "Accountability", "Decisive execution"],
    watchouts: ["Over-control", "Frustration with flexible teammates", "Treating recovery as unproductive"],
    thrive: [
      "Plan weekly targets in advance and review completion at a fixed time.",
      "Use measurable workout, Running and Steps goals to channel competitive discipline.",
      "Build recovery and flexibility into the plan so structure supports progress rather than controlling it.",
    ],
    connections: ["ISFP", "ISTP", "ESFJ"],
  },
  {
    type: "ESFJ",
    title: "The Steward",
    symbol: "🤝",
    primary: "#8c654f",
    secondary: "#f4ebe4",
    tagline: "Community, responsibility, and progress strengthened by shared commitment.",
    strengths: ["Encouragement", "Reliability", "Team awareness"],
    watchouts: ["Overcommitting", "Comparing yourself to others", "Difficulty prioritising personal recovery"],
    thrive: [
      "Use House accountability positively, but compare your habits mainly with your own previous weeks.",
      "Make Water, Fruit and recovery part of caring for your future capacity to help others.",
      "Schedule personal training time before volunteering away all of your available energy.",
    ],
    connections: ["ISTP", "ISFP", "ESTJ"],
  },
  {
    type: "ENFJ",
    title: "The Mentor",
    symbol: "🔥",
    primary: "#9b514c",
    secondary: "#f7e5e3",
    tagline: "Purpose, encouragement, and leadership that turns growth into shared momentum.",
    strengths: ["Encouragement", "Leadership", "Purpose-driven consistency"],
    watchouts: ["Taking responsibility for everyone", "Overtraining for the group", "Neglecting private goals"],
    thrive: [
      "Use your ability to encourage others, but keep personal goals that are not dependent on the House.",
      "Let Reading and Journal reflection turn leadership experiences into practical lessons.",
      "Protect recovery days even when other people still want your energy.",
    ],
    connections: ["INFP", "ISFP", "INTP"],
  },
  {
    type: "ENTJ",
    title: "The Conqueror",
    symbol: "👑",
    primary: "#704d58",
    secondary: "#f0e4e8",
    tagline: "Ambition, direction, and disciplined progress toward demanding goals.",
    strengths: ["Leadership", "Goal orientation", "Strategic execution"],
    watchouts: ["Overreaching", "Impatience", "Turning every habit into a competition"],
    thrive: [
      "Set demanding outcome goals, then judge the week by controllable behaviours rather than only results.",
      "Use Analytics and season standings as feedback without letting them replace recovery or sustainability.",
      "Create deliberate low-intensity targets so long-term ambition survives high-intensity phases.",
    ],
    connections: ["INFP", "INTP", "ISFP"],
  },
];

export const MBTI_PROFILES = Object.freeze(
  profiles.map((profile) => Object.freeze({
    ...profile,
    strengths: Object.freeze([...profile.strengths]),
    watchouts: Object.freeze([...profile.watchouts]),
    thrive: Object.freeze([...profile.thrive]),
    connections: Object.freeze([...profile.connections]),
  })),
);

const PROFILE_MAP = new Map(MBTI_PROFILES.map((profile) => [profile.type, profile]));

export function normalizeMbtiType(value) {
  return String(value ?? "").trim().toUpperCase();
}

export function isValidMbtiType(value) {
  return PROFILE_MAP.has(normalizeMbtiType(value));
}

export function getMbtiProfileByType(value) {
  return PROFILE_MAP.get(normalizeMbtiType(value)) ?? null;
}
