export const MBTI_TYPES = Object.freeze([
  "ISTJ", "ISFJ", "INFJ", "INTJ",
  "ISTP", "ISFP", "INFP", "INTP",
  "ESTP", "ESFP", "ENFP", "ENTP",
  "ESTJ", "ESFJ", "ENFJ", "ENTJ",
]);

const profiles = [
  {
    type: "ISTJ",
    title: "Logistician",
    mythicName: "Ironbound Citadel",
    definingQuality: "Reliability",
    primary: "#374151",
    secondary: "#1e3a8a",
    tagline: "Steady foundations. Deliberate action. Progress that holds when pressure arrives.",
    corePersonality: "Dependable, structured, disciplined, methodical and responsibility-focused.",
    symbolism: "The citadel endures because its foundations are maintained before the storm arrives. Ironbound reflects durability, preparation and duty that does not depend on applause.",
    strengths: [
      "Reliability",
      "Planning",
      "Consistency",
      "Patience",
      "Attention to detail",
      "Practical judgement",
    ],
    watchouts: [
      "Rigidity when circumstances change",
      "Over-attachment to procedure",
      "Excessive caution",
      "Under-celebrating hard-earned progress",
    ],
    thrive: [
      "Use fixed training and logging times so consistency becomes automatic.",
      "Track measurable progress instead of chasing novelty.",
      "When a week goes off-plan, define the smallest acceptable fallback and keep moving.",
    ],
    growthAdvice: "You do not need a perfect plan to honour the plan. Adjust what reality demands, then keep the promise you made to yourself.",
    atBest: "You become the person everyone can depend on when systems fail or pressure rises.",
    archetype: "The fortress people only truly appreciate when the storm arrives.",
    connections: ["ESFP", "ESTP", "ISFJ"],
    motivationStyle: "Calm, concrete and duty-oriented. Respect preparation, consistency and evidence of progress.",
  },
  {
    type: "ISFJ",
    title: "Defender",
    mythicName: "Amber Aegis",
    definingQuality: "Protection",
    primary: "#d97706",
    secondary: "#7f1d1d",
    tagline: "Quiet strength used to protect what matters and preserve what should endure.",
    corePersonality: "Protective, loyal, attentive, service-oriented and quietly caring.",
    symbolism: "The Aegis represents strength used to protect rather than dominate. Amber adds warmth, memory and preservation: a reminder that care can be both gentle and remarkably durable.",
    strengths: [
      "Loyalty",
      "Practical care",
      "Attentiveness",
      "Patience",
      "Reliability",
      "Memory for personal details",
    ],
    watchouts: [
      "Neglecting your own needs",
      "Difficulty saying no",
      "Suppressed resentment",
      "Holding on to familiar patterns too long",
    ],
    thrive: [
      "Build routines as care for your future self: hydration, recovery, movement and rest.",
      "Use a trusted partner or House commitment when accountability helps you show up.",
      "Treat missed goals as information, then calmly restart with the next useful action.",
    ],
    growthAdvice: "Caring for yourself is not withdrawing care from anyone else. Protect the person who has to carry your responsibilities tomorrow.",
    atBest: "You create safety and continuity without needing credit for doing so.",
    archetype: "The shield that refuses to move because people are standing behind it.",
    connections: ["ENTP", "ESTP", "ISTJ"],
    motivationStyle: "Warm, reassuring and practical. Encourage without guilt and connect self-care to dependable service.",
  },
  {
    type: "INFJ",
    title: "Advocate",
    mythicName: "Eclipsed Oracle",
    definingQuality: "Insight",
    primary: "#172554",
    secondary: "#e8d6a2",
    tagline: "See beyond the immediate moment, then turn meaning into deliberate action.",
    corePersonality: "Visionary, introspective, idealistic, empathetic and internally intense.",
    symbolism: "The Oracle represents hidden meaning, pattern recognition and future consequences. The eclipse reflects an outwardly quiet presence with a deep private world and powerful convictions.",
    strengths: [
      "Insight",
      "Empathy",
      "Pattern recognition",
      "Conviction",
      "Long-term thinking",
      "Understanding motivation",
    ],
    watchouts: [
      "Perfectionism",
      "Overthinking",
      "Emotional exhaustion",
      "Carrying problems that are not yours to solve",
    ],
    thrive: [
      "Connect each category to a personal reason so routine actions still feel meaningful.",
      "Use reflection to turn progress into lessons rather than only numbers.",
      "Set a minimum viable day so an imperfect day cannot become zero progress.",
    ],
    growthAdvice: "Your vision matters most when it survives contact with ordinary life. Do one grounded thing today that serves the future you can already see.",
    atBest: "You recognise what a person, group or situation may become before the outcome is obvious.",
    archetype: "The one who sees the road while everyone else is staring at the crossroads.",
    connections: ["ENTP", "ENFP", "ISFJ"],
    motivationStyle: "Purposeful and reflective. Connect action to meaning while preventing perfectionism from stalling movement.",
  },
  {
    type: "INTJ",
    title: "Architect",
    mythicName: "Obsidian Dragon",
    definingQuality: "Mastery",
    primary: "#050509",
    secondary: "#7c3aed",
    tagline: "Strategic patience, independent mastery and power reserved for the right moment.",
    corePersonality: "Strategic, private, self-directed, future-focused and highly selective about effort.",
    symbolism: "The dragon represents accumulated power, intelligence, patience and long-range command. Obsidian adds precision, hardness and an edge formed under pressure.",
    strengths: [
      "Foresight",
      "Systems thinking",
      "Independence",
      "Discipline",
      "Long-term planning",
      "Persistence",
    ],
    watchouts: [
      "Perfectionism",
      "Emotional distance",
      "Dismissiveness",
      "Overplanning instead of executing",
    ],
    thrive: [
      "Treat goals like a system: define inputs, review evidence and change one variable at a time.",
      "Use Analytics to test whether your plan is actually working.",
      "Keep basic habits simple; not every useful action needs optimisation.",
    ],
    growthAdvice: "Stop improving the blueprint for a moment. Execute the next high-value action and let reality give you better data than another hour of theory.",
    atBest: "You build something others thought impossible because you saw the structure long before they did.",
    archetype: "The strategist who rarely moves without knowing why.",
    connections: ["ENFP", "ENTP", "ISTJ"],
    motivationStyle: "Direct, strategic and competence-focused. Challenge wasted motion and appeal to mastery, autonomy and long-term leverage.",
  },
  {
    type: "ISTP",
    title: "Virtuoso",
    mythicName: "Runeforged Titan Hammer",
    definingQuality: "Competence",
    primary: "#292524",
    secondary: "#f97316",
    tagline: "Hands-on mastery, precise action and calm adaptation when reality changes.",
    corePersonality: "Practical, independent, technically minded, adaptable and calm under pressure.",
    symbolism: "A forged hammer represents competence earned through direct interaction with reality. The runes suggest quiet technical mastery: knowledge that becomes useful through skilled hands.",
    strengths: [
      "Troubleshooting",
      "Precision",
      "Mechanical reasoning",
      "Tactical adaptation",
      "Independence",
      "Composure",
    ],
    watchouts: [
      "Boredom with repetition",
      "Emotional distance",
      "Unnecessary risk-taking",
      "Impatience with bureaucracy",
    ],
    thrive: [
      "Use flexible training options that still satisfy the same underlying goal.",
      "Turn workouts and Skill Development into experiments with measurable outcomes.",
      "Keep one short default routine for days when freedom becomes indecision.",
    ],
    growthAdvice: "You learn by doing, so touch the problem. Ten minutes of real practice will teach you more than waiting for the perfect mood.",
    atBest: "You solve the real problem while everyone else is still discussing the theory.",
    archetype: "Give them the broken mechanism and leave them alone.",
    connections: ["ENFJ", "ESFJ", "ESTP"],
    motivationStyle: "Brief, practical and action-first. Offer a concrete challenge, a measurable target and room for autonomy.",
  },
  {
    type: "ISFP",
    title: "Adventurer",
    mythicName: "Moonveil Stag",
    definingQuality: "Authenticity",
    primary: "#cbd5e1",
    secondary: "#0f766e",
    tagline: "Quiet authenticity, instinctive grace and growth that still feels like your own.",
    corePersonality: "Sensitive, authentic, independent, aesthetic and experience-oriented.",
    symbolism: "The stag represents grace, instinct, wilderness and dignity. Moonveil adds privacy, beauty and emotional subtlety without turning sensitivity into fragility.",
    strengths: [
      "Authenticity",
      "Compassion",
      "Aesthetic sensitivity",
      "Adaptability",
      "Observation",
      "Artistic instinct",
    ],
    watchouts: [
      "Avoiding difficult structure",
      "Sensitivity to criticism",
      "Unpredictable withdrawal",
      "Letting the immediate mood steer long-term goals",
    ],
    thrive: [
      "Choose movement and Skill activities that feel personally engaging rather than forcing one ideal routine.",
      "Use visual progress and personal records to make improvement tangible.",
      "Keep weekly goals visible so spontaneity still has a reliable direction.",
    ],
    growthAdvice: "You do not have to become someone else to become stronger. Choose the next action that feels true to you and still moves you forward.",
    atBest: "You remain completely yourself without needing to impose that identity on anyone else.",
    archetype: "Beautiful because it was never meant to be domesticated.",
    connections: ["ENTJ", "ENFJ", "ESFP"],
    motivationStyle: "Gentle, personal and autonomy-respecting. Emphasise authenticity, tangible progress and freedom within a simple direction.",
  },
  {
    type: "INFP",
    title: "Mediator",
    mythicName: "Ethereal World Tree",
    definingQuality: "Meaning",
    primary: "#14532d",
    secondary: "#c4b5fd",
    tagline: "Deep roots, vast inner worlds and progress anchored to what genuinely matters.",
    corePersonality: "Values-driven, imaginative, deeply individualistic, emotionally rich and meaning-oriented.",
    symbolism: "The World Tree links different realms while remaining rooted. It represents a vast unseen inner life, ideals, identity and the ability to protect meaning when practicality alone would discard it.",
    strengths: [
      "Authenticity",
      "Compassion",
      "Creativity",
      "Imagination",
      "Moral conviction",
      "Emotional understanding",
    ],
    watchouts: [
      "Avoidance when reality disappoints",
      "Unrealistic idealisation",
      "Oversensitivity",
      "Difficulty acting when the perfect option does not exist",
    ],
    thrive: [
      "Write down why a goal matters before focusing on its score.",
      "Use Reading, reflection and Skill Development as fuel for identity-based growth.",
      "Create gentle minimums for low-energy days so your values survive imperfect motivation.",
    ],
    growthAdvice: "Your ideals are not betrayed by small imperfect steps. Give the thing you care about a real place in the world today.",
    atBest: "You preserve something meaningful that more pragmatic people might have discarded.",
    archetype: "A quiet exterior containing an entire unseen universe.",
    connections: ["ENTJ", "ENFJ", "ENFP"],
    motivationStyle: "Gentle, values-led and imaginative. Avoid shame; connect small actions to identity, meaning and compassionate persistence.",
  },
  {
    type: "INTP",
    title: "Logician",
    mythicName: "Astral Sphinx",
    definingQuality: "Understanding",
    primary: "#312e81",
    secondary: "#cbd5e1",
    tagline: "Curiosity without borders, questions without fear and understanding beneath the surface.",
    corePersonality: "Curious, theoretical, intellectually independent, exploratory and internally complex.",
    symbolism: "The Sphinx guards knowledge through riddles rather than force. Astral reflects abstraction, science, philosophy and the desire to understand the mechanism beneath appearances.",
    strengths: [
      "Logic",
      "Originality",
      "Conceptual thinking",
      "Pattern recognition",
      "Intellectual honesty",
      "Curiosity",
    ],
    watchouts: [
      "Analysis paralysis",
      "Procrastination",
      "Detachment",
      "Neglecting practical execution",
    ],
    thrive: [
      "Use Analytics and records as experiments: form a hypothesis, test it and review it.",
      "Pair Reading and Skill Development with a concrete output or practice target.",
      "Require five minutes of action before redesigning the plan.",
    ],
    growthAdvice: "You already understand enough to begin. Run the experiment; the result will give you a better question.",
    atBest: "You understand the mechanism underneath a problem everyone else is trying to solve superficially.",
    archetype: "The keeper of questions that lead to deeper questions.",
    connections: ["ENTJ", "ENFJ", "ENTP"],
    motivationStyle: "Curious, concise and intellectually challenging. Frame action as an experiment and resist repetitive hype.",
  },
  {
    type: "ESTP",
    title: "Entrepreneur",
    mythicName: "Stormforged Gungnir",
    definingQuality: "Action",
    primary: "#2563eb",
    secondary: "#64748b",
    tagline: "Read the moment, commit decisively and hit the opening before it disappears.",
    corePersonality: "Bold, reactive, action-oriented, opportunistic and highly aware of immediate reality.",
    symbolism: "Gungnir symbolises decisive accuracy: see the opening, commit and hit the target. Stormforged adds speed, pressure and the confidence to act while conditions are moving.",
    strengths: [
      "Courage",
      "Fast decision-making",
      "Adaptability",
      "Persuasion",
      "Situational awareness",
      "Crisis response",
    ],
    watchouts: [
      "Recklessness",
      "Impulsiveness",
      "Impatience",
      "Ignoring long-term consequences",
    ],
    thrive: [
      "Use short competitive targets, personal records and House goals to create immediate stakes.",
      "Keep training varied while preserving the underlying weekly minimums.",
      "Schedule recovery with the same seriousness as high-intensity effort.",
    ],
    growthAdvice: "The opening is real. Take it—but make the move that tomorrow's version of you will still respect.",
    atBest: "You recognise the opening and act before hesitation closes it.",
    archetype: "The spear is already flying while everyone else is deciding whether to throw it.",
    connections: ["ISFJ", "ISTJ", "ISTP"],
    motivationStyle: "Energetic, blunt and immediate. Use challenge, momentum and visible targets, while explicitly protecting recovery and consequences.",
  },
  {
    type: "ESFP",
    title: "Entertainer",
    mythicName: "Carnival-Crowned Dionysus",
    definingQuality: "Vitality",
    primary: "#7e22ce",
    secondary: "#facc15",
    tagline: "Make the moment vivid, bring people with you and turn effort into something worth remembering.",
    corePersonality: "Expressive, charismatic, experience-focused, spontaneous and socially energetic.",
    symbolism: "Dionysus represents theatre, celebration, emotional liberation, music and immersion in experience. Carnival-Crowned turns that energy into a vivid identity without reducing it to simple partying.",
    strengths: [
      "Charisma",
      "Emotional expression",
      "Spontaneity",
      "Social intuition",
      "Warmth",
      "Adaptability",
    ],
    watchouts: [
      "Impulsiveness",
      "Overstimulation",
      "Avoiding unpleasant realities",
      "Depending too heavily on excitement or social feedback",
    ],
    thrive: [
      "Use House participation and shared challenges to make consistency social and energising.",
      "Rotate Cardio and Skill activities without abandoning the weekly foundations.",
      "Keep one simple weekly planning ritual so long-term goals survive short-term excitement.",
    ],
    growthAdvice: "Bring the energy—but give it somewhere to go. Finish one meaningful thing before chasing the next spark.",
    atBest: "You make ordinary experiences feel vivid, connected and memorable.",
    archetype: "The presence that turns an evening into a story people tell for years.",
    connections: ["ISTJ", "ISFJ", "ENFP"],
    motivationStyle: "Vivid, upbeat and socially energising. Celebrate action sincerely, then redirect excitement toward finishing and recovery.",
  },
  {
    type: "ENFP",
    title: "Campaigner",
    mythicName: "Aurora Pegasus",
    definingQuality: "Possibility",
    primary: "#0f766e",
    secondary: "#db2777",
    tagline: "Freedom, imagination and the conviction that another path is always waiting to be discovered.",
    corePersonality: "Enthusiastic, imaginative, adventurous, emotionally expressive and possibility-seeking.",
    symbolism: "Pegasus represents inspiration and freedom. The aurora adds movement, colour and possibility: a horizon that keeps changing because there is always more to explore.",
    strengths: [
      "Creativity",
      "Optimism",
      "Adaptability",
      "Enthusiasm",
      "Communication",
      "Connection-building",
    ],
    watchouts: [
      "Distraction",
      "Impulsiveness",
      "Difficulty finishing",
      "Resistance to useful structure",
    ],
    thrive: [
      "Choose a small number of priority categories each week while keeping the rest at maintenance level.",
      "Use varied Cardio and Skill Development to satisfy curiosity without replacing the whole plan.",
      "Share goals with supportive people when external energy helps sustain follow-through.",
    ],
    growthAdvice: "You do not need fewer possibilities; you need one possibility carried far enough to become real. Choose it and stay with it today.",
    atBest: "You make people see possibilities where previously there seemed to be none.",
    archetype: "The creature that sees the horizon and immediately wants to know what lies beyond it.",
    connections: ["INTJ", "INFJ", "INFP"],
    motivationStyle: "Hopeful, imaginative and energising. Offer freedom within a small number of commitments and reinforce follow-through without confinement.",
  },
  {
    type: "ENTP",
    title: "Debater",
    mythicName: "Prismatic Kitsune",
    definingQuality: "Ingenuity",
    primary: "#7c3aed",
    secondary: "#22d3ee",
    tagline: "Question the obvious, transform the frame and discover the route nobody else considered.",
    corePersonality: "Inventive, playful, provocative, mentally agile and possibility-driven.",
    symbolism: "Kitsune embody intelligence, transformation, mischief and adaptability. Prismatic reflects the ability to turn one idea and see several interpretations, loopholes and alternative routes.",
    strengths: [
      "Improvisation",
      "Debate",
      "Innovation",
      "Humour",
      "Lateral thinking",
      "Persuasion",
    ],
    watchouts: [
      "Contrarianism for its own sake",
      "Unfinished projects",
      "Boredom with maintenance",
      "Changing direction before evidence arrives",
    ],
    thrive: [
      "Treat training blocks as experiments with a fixed review date instead of changing direction every few days.",
      "Use personal records and Power Plays as puzzles without changing the rules.",
      "Automate boring essentials such as Water, Steps and recovery.",
    ],
    growthAdvice: "You have found another clever alternative. Good. Now prove one of them works before inventing the seventeenth.",
    atBest: "You discover the loophole, shortcut or alternative nobody else noticed.",
    archetype: "The trickster who realises the rules were only assumptions.",
    connections: ["INFJ", "INTJ", "ISFJ"],
    motivationStyle: "Witty, challenging and novelty-aware. Invite experimentation but demand a finish line and a fixed review point.",
  },
  {
    type: "ESTJ",
    title: "Executive",
    mythicName: "Scarlet War Marshal",
    definingQuality: "Order",
    primary: "#b91c1c",
    secondary: "#94a3b8",
    tagline: "Turn intention into organised action and make the standard visible through execution.",
    corePersonality: "Organised, practical, direct, authoritative and execution-oriented.",
    symbolism: "The War Marshal transforms scattered individuals into coordinated action. Scarlet communicates decisiveness and visible force; the role is about making plans function in the real world.",
    strengths: [
      "Organisation",
      "Leadership",
      "Logistics",
      "Discipline",
      "Accountability",
      "Efficiency",
    ],
    watchouts: [
      "Rigidity",
      "Bluntness",
      "Overcontrol",
      "Impatience with ambiguity",
    ],
    thrive: [
      "Plan weekly targets in advance and review completion at a fixed time.",
      "Use measurable workout, Running and Steps goals to channel disciplined effort.",
      "Build recovery and flexibility into the plan so structure supports progress rather than controlling it.",
    ],
    growthAdvice: "Set the standard, then meet it yourself. If the plan no longer serves the mission, change the plan—not the mission.",
    atBest: "You restore order when everyone else is still arguing about what should happen.",
    archetype: "Chaos becomes an army when the Marshal arrives.",
    connections: ["ISFP", "ISTP", "ESFJ"],
    motivationStyle: "Firm, practical and accountable. Use clear standards and direct calls to action; avoid vague inspiration.",
  },
  {
    type: "ESFJ",
    title: "Consul",
    mythicName: "Harvest-Crowned Demeter",
    definingQuality: "Belonging",
    primary: "#ca8a04",
    secondary: "#fb7185",
    tagline: "Cultivate people, rituals and practical care until a group becomes a community.",
    corePersonality: "Socially attentive, nurturing, community-oriented, generous and relationship-focused.",
    symbolism: "Demeter represents nourishment, harvest, continuity, family and community. The harvest crown turns care into visible abundance: what is consistently tended can eventually feed many people.",
    strengths: [
      "Warmth",
      "Cooperation",
      "Hospitality",
      "Loyalty",
      "Social awareness",
      "Practical generosity",
    ],
    watchouts: [
      "Approval-seeking",
      "Sensitivity to rejection",
      "Overcommitting",
      "Comparing yourself too heavily with others",
    ],
    thrive: [
      "Use House accountability positively, but compare your habits mainly with your own previous weeks.",
      "Treat Water, Fruit and recovery as practical care for your future capacity.",
      "Schedule personal training time before volunteering away all of your available energy.",
    ],
    growthAdvice: "You are allowed to belong without earning your place through constant service. Keep one promise today that is only for your own growth.",
    atBest: "You turn groups of individuals into communities where people feel noticed and supported.",
    archetype: "Where they cultivate relationships, belonging begins to grow.",
    connections: ["ISTP", "ISFP", "ESTJ"],
    motivationStyle: "Warm, relational and encouraging. Reinforce belonging while guarding against approval-seeking and self-neglect.",
  },
  {
    type: "ENFJ",
    title: "Protagonist",
    mythicName: "Solar Phoenix",
    definingQuality: "Inspiration",
    primary: "#ca8a04",
    secondary: "#dc2626",
    tagline: "Rise with purpose, then make your own fire bright enough to help others rise too.",
    corePersonality: "Charismatic, people-focused, inspirational, emotionally perceptive and transformational.",
    symbolism: "The Phoenix represents rebirth and transformation. Solar turns that transformation outward: warmth, visibility and energy that can help other people believe change is possible.",
    strengths: [
      "Leadership",
      "Empathy",
      "Encouragement",
      "Persuasion",
      "Social intelligence",
      "Mediation",
    ],
    watchouts: [
      "People-pleasing",
      "Overinvolvement",
      "Emotional pressure",
      "Neglecting private needs",
    ],
    thrive: [
      "Encourage others, but keep personal goals that are not dependent on the House.",
      "Use Reading and reflection to turn leadership experiences into practical lessons.",
      "Protect recovery days even when other people still want your energy.",
    ],
    growthAdvice: "Lead, but do not disappear inside everyone else's needs. Your example is strongest when your own foundation is healthy.",
    atBest: "You make people believe they are capable of more than they thought.",
    archetype: "The flame that teaches others how to rise.",
    connections: ["INFP", "ISFP", "INTP"],
    motivationStyle: "Inspirational and human. Appeal to purpose and example while reminding the player that self-care is part of leadership.",
  },
  {
    type: "ENTJ",
    title: "Commander",
    mythicName: "Crimson Griffin",
    definingQuality: "Command",
    primary: "#991b1b",
    secondary: "#eab308",
    tagline: "See the whole field, choose the objective and organise momentum around the result.",
    corePersonality: "Ambitious, commanding, strategic, decisive and achievement-oriented.",
    symbolism: "The griffin combines the lion's terrestrial authority with the eagle's high vision. Crimson adds drive and visible command: strategy that expects to become execution.",
    strengths: [
      "Leadership",
      "Execution",
      "Organisation",
      "Strategy",
      "Confidence",
      "Decisiveness",
    ],
    watchouts: [
      "Controlling behaviour",
      "Impatience",
      "Excessive work focus",
      "Treating people too instrumentally",
    ],
    thrive: [
      "Set demanding outcome goals, then judge the week by controllable behaviours rather than results alone.",
      "Use Analytics and standings as feedback without letting them replace recovery.",
      "Create deliberate low-intensity targets so long-term ambition survives high-intensity phases.",
    ],
    growthAdvice: "Pick the objective. Remove the excuse. Execute. Then review whether your intensity is building an empire you can actually sustain.",
    atBest: "You take a scattered group with potential and turn it into a functioning force.",
    archetype: "The ruler who sees the whole battlefield and still knows where to strike.",
    connections: ["INFP", "INTP", "ISFP"],
    motivationStyle: "Strong, concise and ambitious. Use challenge and command language, but tie success to sustainable execution rather than domination.",
  },
];

export const MBTI_PROFILES = Object.freeze(
  profiles.map((profile) => Object.freeze({
    ...profile,
    strengths: Object.freeze([...profile.strengths]),
    watchouts: Object.freeze([...profile.watchouts]),
    thrive: Object.freeze([...profile.thrive]),
    connections: Object.freeze([...profile.connections]),
  })),
);

const PROFILE_MAP = new Map(MBTI_PROFILES.map((profile) => [profile.type, profile]));

export function normalizeMbtiType(value) {
  return String(value ?? "").trim().toUpperCase();
}

export function isValidMbtiType(value) {
  return PROFILE_MAP.has(normalizeMbtiType(value));
}

export function getMbtiProfileByType(value) {
  return PROFILE_MAP.get(normalizeMbtiType(value)) ?? null;
}
