export const OPTIONS = {
  fruitType: [
    "Apple",
    "Apricot",
    "Avocado",
    "Banana",
    "Blackberries",
    "Blueberries",
    "Cherries",
    "Coconut",
    "Grapefruit",
    "Grapes",
    "Guava",
    "Kiwi",
    "Lemon",
    "Lime",
    "Lychee",
    "Mango",
    "Melon",
    "Nectarine",
    "Orange",
    "Papaya",
    "Passion Fruit",
    "Peach",
    "Pear",
    "Pineapple",
    "Plum",
    "Pomegranate",
    "Raspberries",
    "Strawberries",
    "Watermelon",
  ],

  exercise: [
    // Chest
    "Push-ups",
    "Bench Press",
    "Incline Bench Press",
    "Decline Bench Press",
    "Chest Fly",
    "Dips",

    // Back
    "Pull-ups",
    "Chin-ups",
    "Lat Pulldown",
    "Seated Row",
    "Barbell Row",
    "Deadlift",

    // Shoulders
    "Shoulder Press",
    "Lateral Raise",
    "Front Raise",
    "Rear Delt Fly",
    "Arnold Press",

    // Arms
    "Bicep Curls",
    "Hammer Curls",
    "Preacher Curl",
    "Tricep Extensions",
    "Tricep Pushdown",
    "Close Grip Bench Press",

    // Legs
    "Squats",
    "Front Squat",
    "Leg Press",
    "Lunges",
    "Romanian Deadlift",
    "Leg Extension",
    "Leg Curl",
    "Calf Raises",

    // Core
    "Sit-ups",
    "Crunches",
    "Plank",
    "Side Plank",
    "Russian Twists",
    "Leg Raises",
    "Mountain Climbers",

    // Cardio
    "Burpees",
    "Running",
    "Walking",
    "Cycling",
    "Swimming",
    "Skipping",
    "Rowing",
    "Elliptical",
    "Stair Climber",
    "Jumping Jacks",
  ],

  activity: [
    "Walking",
    "Running",
    "Jogging",
    "Cycling",
    "Swimming",
    "Skipping",
    "Rowing",
    "Hiking",
    "Elliptical",
    "Stair Climber",
    "Yoga",
    "Pilates",
    "Stretching",
    "Dancing",
  ],

  skill: [
    "Coding",
    "Web Development",
    "Mobile Development",
    "Game Development",
    "Language Learning",
    "Drawing",
    "Painting",
    "Writing",
    "Reading",
    "Cooking",
    "Baking",
    "Photography",
    "Video Editing",
    "Graphic Design",
    "Chess",
    "Instrument Practice",
    "Singing",
    "Public Speaking",
    "Meditation",
    "Typing Practice",
  ],
};