export const OPTIONS = {
  fruitType: [
    "Apple",
    "Banana",
    "Orange",
    "Pear",
    "Grapes",
    "Pineapple",
    "Mango",
    "Other",
  ],

  exercise: [
    "Push-ups",
    "Pull-ups",
    "Dips",
    "Bench Press",
    "Shoulder Press",
    "Bicep Curls",
    "Tricep Extensions",
    "Squats",
    "Lunges",
    "Calf Raises",
    "Sit-ups",
    "Crunches",
    "Plank",
    "Russian Twists",
    "Leg Raises",
    "Burpees",
    "Other",
  ],

  activity: [
    "Walking",
    "Cycling",
    "Swimming",
    "Skipping",
    "Rowing",
    "Hiking",
    "Elliptical",
    "Other",
  ],

  skill: [
    "Coding",
    "Language Learning",
    "Drawing",
    "Writing",
    "Cooking",
    "Chess",
    "Instrument",
    "Public Speaking",
    "Other",
  ],
};