export const FULL_BODY_OPTIONS = [
  { name: "Bear Crawl" },
  { name: "Bodyweight Circuit" },
  { name: "Box Jump" },
  { name: "Broad Jump" },
  { name: "Burpee" },
  { name: "Burpee Pull Up" },
  { name: "Clean" },
  { name: "Clean and Jerk" },
  { name: "Clean and Press" },
  { name: "CrossFit WOD" },
  { name: "Devil Press" },
  { name: "Farmer Carry" },
  { name: "Ground to Overhead" },
  { name: "Hang Clean" },
  { name: "Hang Power Clean" },
  { name: "Kettlebell Clean" },
  { name: "Kettlebell Clean and Press" },
  { name: "Kettlebell Snatch" },
  { name: "Kettlebell Swing" },
  { name: "Log Press" },
  { name: "Medicine Ball Slam" },
  { name: "Power Clean" },
  { name: "Power Snatch" },
  { name: "Sandbag Carry" },
  { name: "Sandbag Clean" },
  { name: "Sandbag Shouldering" },
  { name: "Sled Drag" },
  { name: "Sled Pull" },
  { name: "Sled Push" },
  { name: "Snatch" },
  { name: "Squat to Press" },
  { name: "Thruster" },
  { name: "Turkish Get Up" },
  { name: "Wall Ball" },
  { name: "Wood Chop" },
];