export const LOWER_BODY_OPTIONS = [
  { name: "Barbell Back Squat" },
  { name: "Barbell Front Squat" },
  { name: "Barbell Hip Thrust" },
  { name: "Bulgarian Split Squat" },
  { name: "Cable Kickback" },
  { name: "Calf Press Machine" },
  { name: "Calf Raise" },
  { name: "Curtsy Lunge" },
  { name: "Deadlift" },
  { name: "Donkey Calf Raise" },
  { name: "Dumbbell Deadlift" },
  { name: "Dumbbell Lunge" },
  { name: "Dumbbell Romanian Deadlift" },
  { name: "Goblet Squat" },
  { name: "Glute Bridge" },
  { name: "Good Morning" },
  { name: "Hack Squat" },
  { name: "Hack Squat Machine" },
  { name: "Hamstring Curl Machine" },
  { name: "Hip Abductor Machine" },
  { name: "Hip Adductor Machine" },
  { name: "Hip Thrust" },
  { name: "Jump Squat" },
  { name: "Kettlebell Deadlift" },
  { name: "Kettlebell Swing" },
  { name: "Landmine Squat" },
  { name: "Leg Curl" },
  { name: "Leg Extension" },
  { name: "Leg Press" },
  { name: "Lunge" },
  { name: "Nordic Hamstring Curl" },
  { name: "Pistol Squat" },
  { name: "Reverse Lunge" },
  { name: "Romanian Deadlift" },
  { name: "Seated Calf Raise" },
  { name: "Single Leg Deadlift" },
  { name: "Single Leg Glute Bridge" },
  { name: "Single Leg Press" },
  { name: "Split Squat" },
  { name: "Step Up" },
  { name: "Stiff Leg Deadlift" },
  { name: "Sumo Deadlift" },
  { name: "Sumo Squat" },
  { name: "Trap Bar Deadlift" },
  { name: "Walking Lunge" },
  { name: "Wall Sit" },
]