export const READING_OPTIONS = [
  "Book",
  "Novel",
  "Biography",
  "Autobiography",
  "Self Help",
  "Business",
  "Finance",
  "Investing",
  "Psychology",
  "Science",
  "Technology",
  "Programming",
  "History",
  "Philosophy",
  "Religion",
  "Health",
  "Fitness",
  "Nutrition",
  "Cooking",
  "Language Learning",
  "Comic",
  "Manga",
  "Magazine",
  "Newspaper",
  "Research Paper",
  "Textbook",
  "Other",
];