export const CORE_OPTIONS = [
  { name: "Ab Wheel Rollout" },
  { name: "Bicycle Crunch" },
  { name: "Bird Dog" },
  { name: "Cable Crunch" },
  { name: "Captain's Chair Leg Raise" },
  { name: "Crunch" },
  { name: "Dead Bug" },
  { name: "Dragon Flag" },
  { name: "Flutter Kick" },
  { name: "Hanging Knee Raise" },
  { name: "Hanging Leg Raise" },
  { name: "Heel Touch" },
  { name: "Hollow Body Hold" },
  { name: "Jackknife Sit Up" },
  { name: "Knee Tuck" },
  { name: "L-Sit" },
  { name: "Medicine Ball Russian Twist" },
  { name: "Mountain Climber" },
  { name: "Oblique Crunch" },
  { name: "Pallof Press" },
  { name: "Plank" },
  { name: "Plank Reach" },
  { name: "Reverse Crunch" },
  { name: "Russian Twist" },
  { name: "Side Bend" },
  { name: "Side Plank" },
  { name: "Sit Up" },
  { name: "Stability Ball Crunch" },
  { name: "Stir the Pot" },
  { name: "Superman" },
  { name: "Toe Touch" },
  { name: "Turkish Get Up" },
  { name: "V-Up" },
  { name: "Vacuum Hold" },
  { name: "Windshield Wiper" },
  { name: "Wood Chop" },
];