export const UPPER_BODY_OPTIONS = [
  { name: "Arnold Press" },
  { name: "Australian Row" },
  { name: "Barbell Curl" },
  { name: "Barbell Row" },
  { name: "Battle Rope Slams" },
  { name: "Bench Press" },
  { name: "Cable Curl" },
  { name: "Cable Fly" },
  { name: "Cable Row" },
  { name: "Chest Dip" },
  { name: "Chest Press Machine" },
  { name: "Chest Supported Row" },
  { name: "Chin Up" },
  { name: "Close Grip Bench Press" },
  { name: "Close Grip Pull Up" },
  { name: "Concentration Curl" },
  { name: "Decline Bench Press" },
  { name: "Decline Push Up" },
  { name: "Diamond Push Up" },
  { name: "Dips" },
  { name: "Dumbbell Bench Press" },
  { name: "Dumbbell Curl" },
  { name: "Dumbbell Pullover" },
  { name: "Dumbbell Row" },
  { name: "Dumbbell Shoulder Press" },
  { name: "EZ Bar Curl" },
  { name: "Face Pull" },
  { name: "Farmer Carry" },
  { name: "Flat Bench Dumbbell Fly" },
  { name: "Front Raise" },
  { name: "Hammer Curl" },
  { name: "Handstand Push Up" },
  { name: "High Cable Fly" },
  { name: "Hindu Push Up" },
  { name: "Incline Bench Press" },
  { name: "Incline Dumbbell Press" },
  { name: "Incline Push Up" },
  { name: "Inverted Row" },
  { name: "Lat Pulldown" },
  { name: "Lateral Raise" },
  { name: "Low Cable Fly" },
  { name: "Machine Shoulder Press" },
  { name: "Muscle Up" },
  { name: "Neutral Grip Pull Up" },
  { name: "One Arm Pull Up" },
  { name: "One Arm Push Up" },
  { name: "Overhead Press" },
  { name: "Overhead Tricep Extension" },
  { name: "Pec Deck" },
  { name: "Pike Push Up" },
  { name: "Preacher Curl" },
  { name: "Pseudo Planche Push Up" },
  { name: "Pull Up" },
  { name: "Push Up" },
  { name: "Rear Delt Fly" },
  { name: "Resistance Band Row" },
  { name: "Ring Dip" },
  { name: "Ring Push Up" },
  { name: "Ring Row" },
  { name: "Seated Cable Row" },
  { name: "Seated Dumbbell Press" },
  { name: "Shoulder Press Machine" },
  { name: "Shrugs" },
  { name: "Skull Crusher" },
  { name: "Spiderman Push Up" },
  { name: "Straight Arm Pulldown" },
  { name: "Straight Bar Dip" },
  { name: "T-Bar Row" },
  { name: "Tricep Pushdown" },
  { name: "Typewriter Pull Up" },
  { name: "Upright Row" },
  { name: "Weighted Dip" },
  { name: "Weighted Pull Up" },
  { name: "Wide Grip Pull Up" },
  { name: "Wide Push Up" },
];